-- VHDL netlist generated by SCUBA Diamond_1.4_Production (87)
-- Module  Version: 5.4
--/opt/lattice/diamond/1.4/ispfpga/bin/lin/scuba -w -lang vhdl -synth synplify -bus_exp 7 -bb -arch ep5c00 -type ebfifo -depth 64 -width 64 -depth 64 -rdata_width 8 -no_enable -pe 10 -pe2 12 -pf 63 -pf2 62 -e 

-- Sun Apr  1 13:47:33 2012

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp3;
use ecp3.components.all;
-- synopsys translate_on

entity fifo_512x64x8 is
    port (
        Data: in  std_logic_vector(63 downto 0); 
        WrClock: in  std_logic; 
        RdClock: in  std_logic; 
        WrEn: in  std_logic; 
        RdEn: in  std_logic; 
        Reset: in  std_logic; 
        RPReset: in  std_logic; 
        Q: out  std_logic_vector(7 downto 0); 
        Empty: out  std_logic; 
        Full: out  std_logic; 
        AlmostEmpty: out  std_logic; 
        AlmostFull: out  std_logic);
end fifo_512x64x8;

architecture Structure of fifo_512x64x8 is

    -- internal signal declarations
    signal invout_1: std_logic;
    signal invout_0: std_logic;
    signal rcount_w2: std_logic;
    signal rcount_w1: std_logic;
    signal rcount_w0: std_logic;
    signal r_g2b_xor_cluster_1: std_logic;
    signal w_gdata_0: std_logic;
    signal w_gdata_1: std_logic;
    signal w_gdata_2: std_logic;
    signal w_gdata_3: std_logic;
    signal w_gdata_4: std_logic;
    signal w_gdata_5: std_logic;
    signal wptr_0: std_logic;
    signal wptr_1: std_logic;
    signal wptr_2: std_logic;
    signal wptr_3: std_logic;
    signal wptr_4: std_logic;
    signal wptr_5: std_logic;
    signal wptr_6: std_logic;
    signal r_gdata_0: std_logic;
    signal r_gdata_1: std_logic;
    signal r_gdata_2: std_logic;
    signal r_gdata_3: std_logic;
    signal r_gdata_4: std_logic;
    signal r_gdata_5: std_logic;
    signal r_gdata_6: std_logic;
    signal r_gdata_7: std_logic;
    signal r_gdata_8: std_logic;
    signal rptr_0: std_logic;
    signal rptr_1: std_logic;
    signal rptr_2: std_logic;
    signal rptr_3: std_logic;
    signal rptr_4: std_logic;
    signal rptr_5: std_logic;
    signal rptr_6: std_logic;
    signal rptr_7: std_logic;
    signal rptr_8: std_logic;
    signal rptr_9: std_logic;
    signal w_gcount_0: std_logic;
    signal w_gcount_1: std_logic;
    signal w_gcount_2: std_logic;
    signal w_gcount_3: std_logic;
    signal w_gcount_4: std_logic;
    signal w_gcount_5: std_logic;
    signal w_gcount_6: std_logic;
    signal r_gcount_0: std_logic;
    signal r_gcount_1: std_logic;
    signal r_gcount_2: std_logic;
    signal r_gcount_3: std_logic;
    signal r_gcount_4: std_logic;
    signal r_gcount_5: std_logic;
    signal r_gcount_6: std_logic;
    signal r_gcount_7: std_logic;
    signal r_gcount_8: std_logic;
    signal r_gcount_9: std_logic;
    signal w_gcount_r20: std_logic;
    signal w_gcount_r0: std_logic;
    signal w_gcount_r21: std_logic;
    signal w_gcount_r1: std_logic;
    signal w_gcount_r22: std_logic;
    signal w_gcount_r2: std_logic;
    signal w_gcount_r23: std_logic;
    signal w_gcount_r3: std_logic;
    signal w_gcount_r24: std_logic;
    signal w_gcount_r4: std_logic;
    signal w_gcount_r25: std_logic;
    signal w_gcount_r5: std_logic;
    signal w_gcount_r26: std_logic;
    signal w_gcount_r6: std_logic;
    signal r_gcount_w20: std_logic;
    signal r_gcount_w0: std_logic;
    signal r_gcount_w21: std_logic;
    signal r_gcount_w1: std_logic;
    signal r_gcount_w22: std_logic;
    signal r_gcount_w2: std_logic;
    signal r_gcount_w23: std_logic;
    signal r_gcount_w3: std_logic;
    signal r_gcount_w24: std_logic;
    signal r_gcount_w4: std_logic;
    signal r_gcount_w25: std_logic;
    signal r_gcount_w5: std_logic;
    signal r_gcount_w26: std_logic;
    signal r_gcount_w6: std_logic;
    signal r_gcount_w27: std_logic;
    signal r_gcount_w7: std_logic;
    signal r_gcount_w28: std_logic;
    signal r_gcount_w8: std_logic;
    signal r_gcount_w29: std_logic;
    signal r_gcount_w9: std_logic;
    signal empty_i: std_logic;
    signal full_i: std_logic;
    signal ae: std_logic;
    signal rRst: std_logic;
    signal ae_d: std_logic;
    signal af: std_logic;
    signal af_d: std_logic;
    signal iwcount_0: std_logic;
    signal iwcount_1: std_logic;
    signal w_gctr_ci: std_logic;
    signal iwcount_2: std_logic;
    signal iwcount_3: std_logic;
    signal co0: std_logic;
    signal iwcount_4: std_logic;
    signal iwcount_5: std_logic;
    signal co1: std_logic;
    signal iwcount_6: std_logic;
    signal co3: std_logic;
    signal wcount_6: std_logic;
    signal co2: std_logic;
    signal ircount_0: std_logic;
    signal ircount_1: std_logic;
    signal r_gctr_ci: std_logic;
    signal ircount_2: std_logic;
    signal ircount_3: std_logic;
    signal co0_1: std_logic;
    signal ircount_4: std_logic;
    signal ircount_5: std_logic;
    signal co1_1: std_logic;
    signal ircount_6: std_logic;
    signal ircount_7: std_logic;
    signal co2_1: std_logic;
    signal ircount_8: std_logic;
    signal ircount_9: std_logic;
    signal co4: std_logic;
    signal rcount_9: std_logic;
    signal co3_1: std_logic;
    signal cmp_ci: std_logic;
    signal rcount_0: std_logic;
    signal rcount_1: std_logic;
    signal co0_2: std_logic;
    signal rcount_2: std_logic;
    signal rcount_3: std_logic;
    signal co1_2: std_logic;
    signal rcount_4: std_logic;
    signal rcount_5: std_logic;
    signal co2_2: std_logic;
    signal rcount_6: std_logic;
    signal rcount_7: std_logic;
    signal co3_2: std_logic;
    signal empty_cmp_clr: std_logic;
    signal rcount_8: std_logic;
    signal empty_cmp_set: std_logic;
    signal empty_d: std_logic;
    signal empty_d_c: std_logic;
    signal cmp_ci_1: std_logic;
    signal wcount_0: std_logic;
    signal wcount_1: std_logic;
    signal co0_3: std_logic;
    signal wcount_2: std_logic;
    signal wcount_3: std_logic;
    signal co1_3: std_logic;
    signal wcount_4: std_logic;
    signal wcount_5: std_logic;
    signal co2_3: std_logic;
    signal full_cmp_clr: std_logic;
    signal full_cmp_set: std_logic;
    signal full_d: std_logic;
    signal full_d_c: std_logic;
    signal iae_setcount_0: std_logic;
    signal iae_setcount_1: std_logic;
    signal ae_set_ctr_ci: std_logic;
    signal iae_setcount_2: std_logic;
    signal iae_setcount_3: std_logic;
    signal co0_4: std_logic;
    signal iae_setcount_4: std_logic;
    signal iae_setcount_5: std_logic;
    signal co1_4: std_logic;
    signal iae_setcount_6: std_logic;
    signal iae_setcount_7: std_logic;
    signal co2_4: std_logic;
    signal iae_setcount_8: std_logic;
    signal iae_setcount_9: std_logic;
    signal co4_1: std_logic;
    signal ae_setcount_9: std_logic;
    signal co3_3: std_logic;
    signal cmp_ci_2: std_logic;
    signal ae_setcount_0: std_logic;
    signal ae_setcount_1: std_logic;
    signal co0_5: std_logic;
    signal ae_setcount_2: std_logic;
    signal ae_setcount_3: std_logic;
    signal co1_5: std_logic;
    signal ae_setcount_4: std_logic;
    signal ae_setcount_5: std_logic;
    signal co2_5: std_logic;
    signal ae_setcount_6: std_logic;
    signal ae_setcount_7: std_logic;
    signal co3_4: std_logic;
    signal ae_set_cmp_clr: std_logic;
    signal ae_setcount_8: std_logic;
    signal ae_set_cmp_set: std_logic;
    signal ae_set_d: std_logic;
    signal ae_set_d_c: std_logic;
    signal iae_clrcount_0: std_logic;
    signal iae_clrcount_1: std_logic;
    signal ae_clr_ctr_ci: std_logic;
    signal iae_clrcount_2: std_logic;
    signal iae_clrcount_3: std_logic;
    signal co0_6: std_logic;
    signal iae_clrcount_4: std_logic;
    signal iae_clrcount_5: std_logic;
    signal co1_6: std_logic;
    signal iae_clrcount_6: std_logic;
    signal iae_clrcount_7: std_logic;
    signal co2_6: std_logic;
    signal iae_clrcount_8: std_logic;
    signal iae_clrcount_9: std_logic;
    signal co4_2: std_logic;
    signal ae_clrcount_9: std_logic;
    signal co3_5: std_logic;
    signal rden_i: std_logic;
    signal cmp_ci_3: std_logic;
    signal ae_clrcount_0: std_logic;
    signal ae_clrcount_1: std_logic;
    signal co0_7: std_logic;
    signal wcount_r0: std_logic;
    signal ae_clrcount_2: std_logic;
    signal ae_clrcount_3: std_logic;
    signal co1_7: std_logic;
    signal wcount_r1: std_logic;
    signal wcount_r2: std_logic;
    signal ae_clrcount_4: std_logic;
    signal ae_clrcount_5: std_logic;
    signal co2_7: std_logic;
    signal w_g2b_xor_cluster_0: std_logic;
    signal wcount_r4: std_logic;
    signal ae_clrcount_6: std_logic;
    signal ae_clrcount_7: std_logic;
    signal co3_6: std_logic;
    signal wcount_r5: std_logic;
    signal ae_clr_cmp_clr: std_logic;
    signal ae_clrcount_8: std_logic;
    signal ae_clr_cmp_set: std_logic;
    signal ae_clr_d: std_logic;
    signal ae_clr_d_c: std_logic;
    signal iaf_setcount_0: std_logic;
    signal iaf_setcount_1: std_logic;
    signal af_set_ctr_ci: std_logic;
    signal iaf_setcount_2: std_logic;
    signal iaf_setcount_3: std_logic;
    signal co0_8: std_logic;
    signal iaf_setcount_4: std_logic;
    signal iaf_setcount_5: std_logic;
    signal co1_8: std_logic;
    signal iaf_setcount_6: std_logic;
    signal co3_7: std_logic;
    signal af_setcount_6: std_logic;
    signal co2_8: std_logic;
    signal cmp_ci_4: std_logic;
    signal af_setcount_0: std_logic;
    signal af_setcount_1: std_logic;
    signal co0_9: std_logic;
    signal af_setcount_2: std_logic;
    signal af_setcount_3: std_logic;
    signal co1_9: std_logic;
    signal af_setcount_4: std_logic;
    signal af_setcount_5: std_logic;
    signal co2_9: std_logic;
    signal af_set_cmp_clr: std_logic;
    signal af_set_cmp_set: std_logic;
    signal af_set: std_logic;
    signal af_set_c: std_logic;
    signal scuba_vhi: std_logic;
    signal iaf_clrcount_0: std_logic;
    signal iaf_clrcount_1: std_logic;
    signal af_clr_ctr_ci: std_logic;
    signal iaf_clrcount_2: std_logic;
    signal iaf_clrcount_3: std_logic;
    signal co0_10: std_logic;
    signal iaf_clrcount_4: std_logic;
    signal iaf_clrcount_5: std_logic;
    signal co1_10: std_logic;
    signal iaf_clrcount_6: std_logic;
    signal co3_8: std_logic;
    signal af_clrcount_6: std_logic;
    signal co2_10: std_logic;
    signal wren_i: std_logic;
    signal cmp_ci_5: std_logic;
    signal rcount_w3: std_logic;
    signal rcount_w4: std_logic;
    signal af_clrcount_0: std_logic;
    signal af_clrcount_1: std_logic;
    signal co0_11: std_logic;
    signal rcount_w5: std_logic;
    signal r_g2b_xor_cluster_0: std_logic;
    signal af_clrcount_2: std_logic;
    signal af_clrcount_3: std_logic;
    signal co1_11: std_logic;
    signal rcount_w7: std_logic;
    signal rcount_w8: std_logic;
    signal af_clrcount_4: std_logic;
    signal af_clrcount_5: std_logic;
    signal co2_11: std_logic;
    signal af_clr_cmp_clr: std_logic;
    signal af_clr_cmp_set: std_logic;
    signal af_clr: std_logic;
    signal af_clr_c: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component AGEB2
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; GE: out  std_logic);
    end component;
    component AND2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component CU2
        port (CI: in  std_logic; PC0: in  std_logic; PC1: in  std_logic; 
            CO: out  std_logic; NC0: out  std_logic; NC1: out  std_logic);
    end component;
    component FADD2B
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; COUT: out  std_logic; 
            S0: out  std_logic; S1: out  std_logic);
    end component;
    component FD1P3BX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            PD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1S3BX
        port (D: in  std_logic; CK: in  std_logic; PD: in  std_logic; 
            Q: out  std_logic);
    end component;
    component FD1S3DX
        port (D: in  std_logic; CK: in  std_logic; CD: in  std_logic; 
            Q: out  std_logic);
    end component;
    component INV
        port (A: in  std_logic; Z: out  std_logic);
    end component;
    component OR2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component ROM16X1A
        generic (INITVAL : in std_logic_vector(15 downto 0));
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component XOR2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component PDPW16KC
        generic (GSR : in String; CSDECODE_R : in String; 
                CSDECODE_W : in String; REGMODE : in String; 
                DATA_WIDTH_R : in Integer; DATA_WIDTH_W : in Integer);
        port (DI0: in  std_logic; DI1: in  std_logic; DI2: in  std_logic; 
            DI3: in  std_logic; DI4: in  std_logic; DI5: in  std_logic; 
            DI6: in  std_logic; DI7: in  std_logic; DI8: in  std_logic; 
            DI9: in  std_logic; DI10: in  std_logic; DI11: in  std_logic; 
            DI12: in  std_logic; DI13: in  std_logic; 
            DI14: in  std_logic; DI15: in  std_logic; 
            DI16: in  std_logic; DI17: in  std_logic; 
            DI18: in  std_logic; DI19: in  std_logic; 
            DI20: in  std_logic; DI21: in  std_logic; 
            DI22: in  std_logic; DI23: in  std_logic; 
            DI24: in  std_logic; DI25: in  std_logic; 
            DI26: in  std_logic; DI27: in  std_logic; 
            DI28: in  std_logic; DI29: in  std_logic; 
            DI30: in  std_logic; DI31: in  std_logic; 
            DI32: in  std_logic; DI33: in  std_logic; 
            DI34: in  std_logic; DI35: in  std_logic; 
            ADW0: in  std_logic; ADW1: in  std_logic; 
            ADW2: in  std_logic; ADW3: in  std_logic; 
            ADW4: in  std_logic; ADW5: in  std_logic; 
            ADW6: in  std_logic; ADW7: in  std_logic; 
            ADW8: in  std_logic; BE0: in  std_logic; BE1: in  std_logic; 
            BE2: in  std_logic; BE3: in  std_logic; CEW: in  std_logic; 
            CLKW: in  std_logic; CSW0: in  std_logic; 
            CSW1: in  std_logic; CSW2: in  std_logic; 
            ADR0: in  std_logic; ADR1: in  std_logic; 
            ADR2: in  std_logic; ADR3: in  std_logic; 
            ADR4: in  std_logic; ADR5: in  std_logic; 
            ADR6: in  std_logic; ADR7: in  std_logic; 
            ADR8: in  std_logic; ADR9: in  std_logic; 
            ADR10: in  std_logic; ADR11: in  std_logic; 
            ADR12: in  std_logic; ADR13: in  std_logic; 
            CER: in  std_logic; CLKR: in  std_logic; CSR0: in  std_logic; 
            CSR1: in  std_logic; CSR2: in  std_logic; RST: in  std_logic; 
            DO0: out  std_logic; DO1: out  std_logic; 
            DO2: out  std_logic; DO3: out  std_logic; 
            DO4: out  std_logic; DO5: out  std_logic; 
            DO6: out  std_logic; DO7: out  std_logic; 
            DO8: out  std_logic; DO9: out  std_logic; 
            DO10: out  std_logic; DO11: out  std_logic; 
            DO12: out  std_logic; DO13: out  std_logic; 
            DO14: out  std_logic; DO15: out  std_logic; 
            DO16: out  std_logic; DO17: out  std_logic; 
            DO18: out  std_logic; DO19: out  std_logic; 
            DO20: out  std_logic; DO21: out  std_logic; 
            DO22: out  std_logic; DO23: out  std_logic; 
            DO24: out  std_logic; DO25: out  std_logic; 
            DO26: out  std_logic; DO27: out  std_logic; 
            DO28: out  std_logic; DO29: out  std_logic; 
            DO30: out  std_logic; DO31: out  std_logic; 
            DO32: out  std_logic; DO33: out  std_logic; 
            DO34: out  std_logic; DO35: out  std_logic);
    end component;
    attribute MEM_LPC_FILE : string; 
    attribute MEM_INIT_FILE : string; 
    attribute RESETMODE : string; 
    attribute GSR : string; 
    attribute MEM_LPC_FILE of pdp_ram_0_0_1 : label is "fifo_512x64x8.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_0_1 : label is "";
    attribute RESETMODE of pdp_ram_0_0_1 : label is "SYNC";
    attribute MEM_LPC_FILE of pdp_ram_0_1_0 : label is "fifo_512x64x8.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_1_0 : label is "";
    attribute RESETMODE of pdp_ram_0_1_0 : label is "SYNC";
    attribute GSR of FF_122 : label is "ENABLED";
    attribute GSR of FF_121 : label is "ENABLED";
    attribute GSR of FF_120 : label is "ENABLED";
    attribute GSR of FF_119 : label is "ENABLED";
    attribute GSR of FF_118 : label is "ENABLED";
    attribute GSR of FF_117 : label is "ENABLED";
    attribute GSR of FF_116 : label is "ENABLED";
    attribute GSR of FF_115 : label is "ENABLED";
    attribute GSR of FF_114 : label is "ENABLED";
    attribute GSR of FF_113 : label is "ENABLED";
    attribute GSR of FF_112 : label is "ENABLED";
    attribute GSR of FF_111 : label is "ENABLED";
    attribute GSR of FF_110 : label is "ENABLED";
    attribute GSR of FF_109 : label is "ENABLED";
    attribute GSR of FF_108 : label is "ENABLED";
    attribute GSR of FF_107 : label is "ENABLED";
    attribute GSR of FF_106 : label is "ENABLED";
    attribute GSR of FF_105 : label is "ENABLED";
    attribute GSR of FF_104 : label is "ENABLED";
    attribute GSR of FF_103 : label is "ENABLED";
    attribute GSR of FF_102 : label is "ENABLED";
    attribute GSR of FF_101 : label is "ENABLED";
    attribute GSR of FF_100 : label is "ENABLED";
    attribute GSR of FF_99 : label is "ENABLED";
    attribute GSR of FF_98 : label is "ENABLED";
    attribute GSR of FF_97 : label is "ENABLED";
    attribute GSR of FF_96 : label is "ENABLED";
    attribute GSR of FF_95 : label is "ENABLED";
    attribute GSR of FF_94 : label is "ENABLED";
    attribute GSR of FF_93 : label is "ENABLED";
    attribute GSR of FF_92 : label is "ENABLED";
    attribute GSR of FF_91 : label is "ENABLED";
    attribute GSR of FF_90 : label is "ENABLED";
    attribute GSR of FF_89 : label is "ENABLED";
    attribute GSR of FF_88 : label is "ENABLED";
    attribute GSR of FF_87 : label is "ENABLED";
    attribute GSR of FF_86 : label is "ENABLED";
    attribute GSR of FF_85 : label is "ENABLED";
    attribute GSR of FF_84 : label is "ENABLED";
    attribute GSR of FF_83 : label is "ENABLED";
    attribute GSR of FF_82 : label is "ENABLED";
    attribute GSR of FF_81 : label is "ENABLED";
    attribute GSR of FF_80 : label is "ENABLED";
    attribute GSR of FF_79 : label is "ENABLED";
    attribute GSR of FF_78 : label is "ENABLED";
    attribute GSR of FF_77 : label is "ENABLED";
    attribute GSR of FF_76 : label is "ENABLED";
    attribute GSR of FF_75 : label is "ENABLED";
    attribute GSR of FF_74 : label is "ENABLED";
    attribute GSR of FF_73 : label is "ENABLED";
    attribute GSR of FF_72 : label is "ENABLED";
    attribute GSR of FF_71 : label is "ENABLED";
    attribute GSR of FF_70 : label is "ENABLED";
    attribute GSR of FF_69 : label is "ENABLED";
    attribute GSR of FF_68 : label is "ENABLED";
    attribute GSR of FF_67 : label is "ENABLED";
    attribute GSR of FF_66 : label is "ENABLED";
    attribute GSR of FF_65 : label is "ENABLED";
    attribute GSR of FF_64 : label is "ENABLED";
    attribute GSR of FF_63 : label is "ENABLED";
    attribute GSR of FF_62 : label is "ENABLED";
    attribute GSR of FF_61 : label is "ENABLED";
    attribute GSR of FF_60 : label is "ENABLED";
    attribute GSR of FF_59 : label is "ENABLED";
    attribute GSR of FF_58 : label is "ENABLED";
    attribute GSR of FF_57 : label is "ENABLED";
    attribute GSR of FF_56 : label is "ENABLED";
    attribute GSR of FF_55 : label is "ENABLED";
    attribute GSR of FF_54 : label is "ENABLED";
    attribute GSR of FF_53 : label is "ENABLED";
    attribute GSR of FF_52 : label is "ENABLED";
    attribute GSR of FF_51 : label is "ENABLED";
    attribute GSR of FF_50 : label is "ENABLED";
    attribute GSR of FF_49 : label is "ENABLED";
    attribute GSR of FF_48 : label is "ENABLED";
    attribute GSR of FF_47 : label is "ENABLED";
    attribute GSR of FF_46 : label is "ENABLED";
    attribute GSR of FF_45 : label is "ENABLED";
    attribute GSR of FF_44 : label is "ENABLED";
    attribute GSR of FF_43 : label is "ENABLED";
    attribute GSR of FF_42 : label is "ENABLED";
    attribute GSR of FF_41 : label is "ENABLED";
    attribute GSR of FF_40 : label is "ENABLED";
    attribute GSR of FF_39 : label is "ENABLED";
    attribute GSR of FF_38 : label is "ENABLED";
    attribute GSR of FF_37 : label is "ENABLED";
    attribute GSR of FF_36 : label is "ENABLED";
    attribute GSR of FF_35 : label is "ENABLED";
    attribute GSR of FF_34 : label is "ENABLED";
    attribute GSR of FF_33 : label is "ENABLED";
    attribute GSR of FF_32 : label is "ENABLED";
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;

begin
    -- component instantiation statements
    AND2_t17: AND2
        port map (A=>WrEn, B=>invout_1, Z=>wren_i);

    INV_1: INV
        port map (A=>full_i, Z=>invout_1);

    AND2_t16: AND2
        port map (A=>RdEn, B=>invout_0, Z=>rden_i);

    INV_0: INV
        port map (A=>empty_i, Z=>invout_0);

    OR2_t15: OR2
        port map (A=>Reset, B=>RPReset, Z=>rRst);

    XOR2_t14: XOR2
        port map (A=>wcount_0, B=>wcount_1, Z=>w_gdata_0);

    XOR2_t13: XOR2
        port map (A=>wcount_1, B=>wcount_2, Z=>w_gdata_1);

    XOR2_t12: XOR2
        port map (A=>wcount_2, B=>wcount_3, Z=>w_gdata_2);

    XOR2_t11: XOR2
        port map (A=>wcount_3, B=>wcount_4, Z=>w_gdata_3);

    XOR2_t10: XOR2
        port map (A=>wcount_4, B=>wcount_5, Z=>w_gdata_4);

    XOR2_t9: XOR2
        port map (A=>wcount_5, B=>wcount_6, Z=>w_gdata_5);

    XOR2_t8: XOR2
        port map (A=>rcount_0, B=>rcount_1, Z=>r_gdata_0);

    XOR2_t7: XOR2
        port map (A=>rcount_1, B=>rcount_2, Z=>r_gdata_1);

    XOR2_t6: XOR2
        port map (A=>rcount_2, B=>rcount_3, Z=>r_gdata_2);

    XOR2_t5: XOR2
        port map (A=>rcount_3, B=>rcount_4, Z=>r_gdata_3);

    XOR2_t4: XOR2
        port map (A=>rcount_4, B=>rcount_5, Z=>r_gdata_4);

    XOR2_t3: XOR2
        port map (A=>rcount_5, B=>rcount_6, Z=>r_gdata_5);

    XOR2_t2: XOR2
        port map (A=>rcount_6, B=>rcount_7, Z=>r_gdata_6);

    XOR2_t1: XOR2
        port map (A=>rcount_7, B=>rcount_8, Z=>r_gdata_7);

    XOR2_t0: XOR2
        port map (A=>rcount_8, B=>rcount_9, Z=>r_gdata_8);

    LUT4_29: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r23, AD2=>w_gcount_r24, 
            AD1=>w_gcount_r25, AD0=>w_gcount_r26, 
            DO0=>w_g2b_xor_cluster_0);

    LUT4_28: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r25, AD2=>w_gcount_r26, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>wcount_r5);

    LUT4_27: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r24, AD2=>w_gcount_r25, 
            AD1=>w_gcount_r26, AD0=>scuba_vlo, DO0=>wcount_r4);

    LUT4_26: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r22, AD2=>w_gcount_r23, 
            AD1=>w_gcount_r24, AD0=>wcount_r5, DO0=>wcount_r2);

    LUT4_25: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r21, AD2=>w_gcount_r22, 
            AD1=>w_gcount_r23, AD0=>wcount_r4, DO0=>wcount_r1);

    LUT4_24: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r20, AD2=>w_gcount_r21, 
            AD1=>w_gcount_r22, AD0=>w_g2b_xor_cluster_0, DO0=>wcount_r0);

    LUT4_23: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w26, AD2=>r_gcount_w27, 
            AD1=>r_gcount_w28, AD0=>r_gcount_w29, 
            DO0=>r_g2b_xor_cluster_0);

    LUT4_22: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w22, AD2=>r_gcount_w23, 
            AD1=>r_gcount_w24, AD0=>r_gcount_w25, 
            DO0=>r_g2b_xor_cluster_1);

    LUT4_21: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w28, AD2=>r_gcount_w29, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>rcount_w8);

    LUT4_20: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w27, AD2=>r_gcount_w28, 
            AD1=>r_gcount_w29, AD0=>scuba_vlo, DO0=>rcount_w7);

    LUT4_19: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w25, AD2=>r_gcount_w26, 
            AD1=>r_gcount_w27, AD0=>rcount_w8, DO0=>rcount_w5);

    LUT4_18: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w24, AD2=>r_gcount_w25, 
            AD1=>r_gcount_w26, AD0=>rcount_w7, DO0=>rcount_w4);

    LUT4_17: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w23, AD2=>r_gcount_w24, 
            AD1=>r_gcount_w25, AD0=>r_g2b_xor_cluster_0, DO0=>rcount_w3);

    LUT4_16: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>scuba_vlo, AD0=>scuba_vlo, DO0=>rcount_w2);

    LUT4_15: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w21, AD0=>scuba_vlo, DO0=>rcount_w1);

    LUT4_14: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w20, AD0=>r_gcount_w21, DO0=>rcount_w0);

    LUT4_13: ROM16X1A
        generic map (initval=> X"0410")
        port map (AD3=>rptr_9, AD2=>rcount_9, AD1=>w_gcount_r26, 
            AD0=>scuba_vlo, DO0=>empty_cmp_set);

    LUT4_12: ROM16X1A
        generic map (initval=> X"1004")
        port map (AD3=>rptr_9, AD2=>rcount_9, AD1=>w_gcount_r26, 
            AD0=>scuba_vlo, DO0=>empty_cmp_clr);

    LUT4_11: ROM16X1A
        generic map (initval=> X"0140")
        port map (AD3=>wptr_6, AD2=>wcount_6, AD1=>r_gcount_w29, 
            AD0=>scuba_vlo, DO0=>full_cmp_set);

    LUT4_10: ROM16X1A
        generic map (initval=> X"4001")
        port map (AD3=>wptr_6, AD2=>wcount_6, AD1=>r_gcount_w29, 
            AD0=>scuba_vlo, DO0=>full_cmp_clr);

    LUT4_9: ROM16X1A
        generic map (initval=> X"13c8")
        port map (AD3=>ae_setcount_9, AD2=>rcount_9, AD1=>w_gcount_r26, 
            AD0=>rptr_9, DO0=>ae_set_cmp_set);

    LUT4_8: ROM16X1A
        generic map (initval=> X"2004")
        port map (AD3=>ae_setcount_9, AD2=>rcount_9, AD1=>w_gcount_r26, 
            AD0=>rptr_9, DO0=>ae_set_cmp_clr);

    LUT4_7: ROM16X1A
        generic map (initval=> X"13c8")
        port map (AD3=>ae_clrcount_9, AD2=>rcount_9, AD1=>w_gcount_r26, 
            AD0=>rptr_9, DO0=>ae_clr_cmp_set);

    LUT4_6: ROM16X1A
        generic map (initval=> X"2004")
        port map (AD3=>ae_clrcount_9, AD2=>rcount_9, AD1=>w_gcount_r26, 
            AD0=>rptr_9, DO0=>ae_clr_cmp_clr);

    LUT4_5: ROM16X1A
        generic map (initval=> X"4450")
        port map (AD3=>ae, AD2=>ae_set_d, AD1=>ae_clr_d, AD0=>scuba_vlo, 
            DO0=>ae_d);

    LUT4_4: ROM16X1A
        generic map (initval=> X"4c32")
        port map (AD3=>af_setcount_6, AD2=>wcount_6, AD1=>r_gcount_w29, 
            AD0=>wptr_6, DO0=>af_set_cmp_set);

    LUT4_3: ROM16X1A
        generic map (initval=> X"8001")
        port map (AD3=>af_setcount_6, AD2=>wcount_6, AD1=>r_gcount_w29, 
            AD0=>wptr_6, DO0=>af_set_cmp_clr);

    LUT4_2: ROM16X1A
        generic map (initval=> X"4c32")
        port map (AD3=>af_clrcount_6, AD2=>wcount_6, AD1=>r_gcount_w29, 
            AD0=>wptr_6, DO0=>af_clr_cmp_set);

    LUT4_1: ROM16X1A
        generic map (initval=> X"8001")
        port map (AD3=>af_clrcount_6, AD2=>wcount_6, AD1=>r_gcount_w29, 
            AD0=>wptr_6, DO0=>af_clr_cmp_clr);

    LUT4_0: ROM16X1A
        generic map (initval=> X"4450")
        port map (AD3=>af, AD2=>af_set, AD1=>af_clr, AD0=>scuba_vlo, 
            DO0=>af_d);

    pdp_ram_0_0_1: PDPW16KC
        generic map (CSDECODE_R=> "0b000", CSDECODE_W=> "0b001", GSR=> "DISABLED", 
        REGMODE=> "NOREG", DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  36)
        port map (DI0=>Data(0), DI1=>Data(1), DI2=>Data(2), DI3=>Data(3), 
            DI4=>Data(8), DI5=>Data(9), DI6=>Data(10), DI7=>Data(11), 
            DI8=>scuba_vlo, DI9=>Data(16), DI10=>Data(17), 
            DI11=>Data(18), DI12=>Data(19), DI13=>Data(24), 
            DI14=>Data(25), DI15=>Data(26), DI16=>Data(27), 
            DI17=>scuba_vlo, DI18=>Data(32), DI19=>Data(33), 
            DI20=>Data(34), DI21=>Data(35), DI22=>Data(40), 
            DI23=>Data(41), DI24=>Data(42), DI25=>Data(43), 
            DI26=>scuba_vlo, DI27=>Data(48), DI28=>Data(49), 
            DI29=>Data(50), DI30=>Data(51), DI31=>Data(56), 
            DI32=>Data(57), DI33=>Data(58), DI34=>Data(59), 
            DI35=>scuba_vlo, ADW0=>wptr_0, ADW1=>wptr_1, ADW2=>wptr_2, 
            ADW3=>wptr_3, ADW4=>wptr_4, ADW5=>wptr_5, ADW6=>scuba_vlo, 
            ADW7=>scuba_vlo, ADW8=>scuba_vlo, BE0=>scuba_vhi, 
            BE1=>scuba_vhi, BE2=>scuba_vhi, BE3=>scuba_vhi, CEW=>wren_i, 
            CLKW=>WrClock, CSW0=>scuba_vhi, CSW1=>scuba_vlo, 
            CSW2=>scuba_vlo, ADR0=>scuba_vlo, ADR1=>scuba_vlo, 
            ADR2=>rptr_0, ADR3=>rptr_1, ADR4=>rptr_2, ADR5=>rptr_3, 
            ADR6=>rptr_4, ADR7=>rptr_5, ADR8=>rptr_6, ADR9=>rptr_7, 
            ADR10=>rptr_8, ADR11=>scuba_vlo, ADR12=>scuba_vlo, 
            ADR13=>scuba_vlo, CER=>rden_i, CLKR=>RdClock, 
            CSR0=>scuba_vlo, CSR1=>scuba_vlo, CSR2=>scuba_vlo, 
            RST=>Reset, DO0=>Q(0), DO1=>Q(1), DO2=>Q(2), DO3=>Q(3), 
            DO4=>open, DO5=>open, DO6=>open, DO7=>open, DO8=>open, 
            DO9=>open, DO10=>open, DO11=>open, DO12=>open, DO13=>open, 
            DO14=>open, DO15=>open, DO16=>open, DO17=>open, DO18=>open, 
            DO19=>open, DO20=>open, DO21=>open, DO22=>open, DO23=>open, 
            DO24=>open, DO25=>open, DO26=>open, DO27=>open, DO28=>open, 
            DO29=>open, DO30=>open, DO31=>open, DO32=>open, DO33=>open, 
            DO34=>open, DO35=>open);

    pdp_ram_0_1_0: PDPW16KC
        generic map (CSDECODE_R=> "0b000", CSDECODE_W=> "0b001", GSR=> "DISABLED", 
        REGMODE=> "NOREG", DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  36)
        port map (DI0=>Data(4), DI1=>Data(5), DI2=>Data(6), DI3=>Data(7), 
            DI4=>Data(12), DI5=>Data(13), DI6=>Data(14), DI7=>Data(15), 
            DI8=>scuba_vlo, DI9=>Data(20), DI10=>Data(21), 
            DI11=>Data(22), DI12=>Data(23), DI13=>Data(28), 
            DI14=>Data(29), DI15=>Data(30), DI16=>Data(31), 
            DI17=>scuba_vlo, DI18=>Data(36), DI19=>Data(37), 
            DI20=>Data(38), DI21=>Data(39), DI22=>Data(44), 
            DI23=>Data(45), DI24=>Data(46), DI25=>Data(47), 
            DI26=>scuba_vlo, DI27=>Data(52), DI28=>Data(53), 
            DI29=>Data(54), DI30=>Data(55), DI31=>Data(60), 
            DI32=>Data(61), DI33=>Data(62), DI34=>Data(63), 
            DI35=>scuba_vlo, ADW0=>wptr_0, ADW1=>wptr_1, ADW2=>wptr_2, 
            ADW3=>wptr_3, ADW4=>wptr_4, ADW5=>wptr_5, ADW6=>scuba_vlo, 
            ADW7=>scuba_vlo, ADW8=>scuba_vlo, BE0=>scuba_vhi, 
            BE1=>scuba_vhi, BE2=>scuba_vhi, BE3=>scuba_vhi, CEW=>wren_i, 
            CLKW=>WrClock, CSW0=>scuba_vhi, CSW1=>scuba_vlo, 
            CSW2=>scuba_vlo, ADR0=>scuba_vlo, ADR1=>scuba_vlo, 
            ADR2=>rptr_0, ADR3=>rptr_1, ADR4=>rptr_2, ADR5=>rptr_3, 
            ADR6=>rptr_4, ADR7=>rptr_5, ADR8=>rptr_6, ADR9=>rptr_7, 
            ADR10=>rptr_8, ADR11=>scuba_vlo, ADR12=>scuba_vlo, 
            ADR13=>scuba_vlo, CER=>rden_i, CLKR=>RdClock, 
            CSR0=>scuba_vlo, CSR1=>scuba_vlo, CSR2=>scuba_vlo, 
            RST=>Reset, DO0=>Q(4), DO1=>Q(5), DO2=>Q(6), DO3=>Q(7), 
            DO4=>open, DO5=>open, DO6=>open, DO7=>open, DO8=>open, 
            DO9=>open, DO10=>open, DO11=>open, DO12=>open, DO13=>open, 
            DO14=>open, DO15=>open, DO16=>open, DO17=>open, DO18=>open, 
            DO19=>open, DO20=>open, DO21=>open, DO22=>open, DO23=>open, 
            DO24=>open, DO25=>open, DO26=>open, DO27=>open, DO28=>open, 
            DO29=>open, DO30=>open, DO31=>open, DO32=>open, DO33=>open, 
            DO34=>open, DO35=>open);

    FF_122: FD1P3BX
        port map (D=>iwcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>wcount_0);

    FF_121: FD1P3DX
        port map (D=>iwcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_1);

    FF_120: FD1P3DX
        port map (D=>iwcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_2);

    FF_119: FD1P3DX
        port map (D=>iwcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_3);

    FF_118: FD1P3DX
        port map (D=>iwcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_4);

    FF_117: FD1P3DX
        port map (D=>iwcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_5);

    FF_116: FD1P3DX
        port map (D=>iwcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_6);

    FF_115: FD1P3DX
        port map (D=>w_gdata_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_0);

    FF_114: FD1P3DX
        port map (D=>w_gdata_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_1);

    FF_113: FD1P3DX
        port map (D=>w_gdata_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_2);

    FF_112: FD1P3DX
        port map (D=>w_gdata_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_3);

    FF_111: FD1P3DX
        port map (D=>w_gdata_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_4);

    FF_110: FD1P3DX
        port map (D=>w_gdata_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_5);

    FF_109: FD1P3DX
        port map (D=>wcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_6);

    FF_108: FD1P3DX
        port map (D=>wcount_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_0);

    FF_107: FD1P3DX
        port map (D=>wcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_1);

    FF_106: FD1P3DX
        port map (D=>wcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_2);

    FF_105: FD1P3DX
        port map (D=>wcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_3);

    FF_104: FD1P3DX
        port map (D=>wcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_4);

    FF_103: FD1P3DX
        port map (D=>wcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_5);

    FF_102: FD1P3DX
        port map (D=>wcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_6);

    FF_101: FD1P3BX
        port map (D=>ircount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>rcount_0);

    FF_100: FD1P3DX
        port map (D=>ircount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_1);

    FF_99: FD1P3DX
        port map (D=>ircount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_2);

    FF_98: FD1P3DX
        port map (D=>ircount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_3);

    FF_97: FD1P3DX
        port map (D=>ircount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_4);

    FF_96: FD1P3DX
        port map (D=>ircount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_5);

    FF_95: FD1P3DX
        port map (D=>ircount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_6);

    FF_94: FD1P3DX
        port map (D=>ircount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_7);

    FF_93: FD1P3DX
        port map (D=>ircount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_8);

    FF_92: FD1P3DX
        port map (D=>ircount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_9);

    FF_91: FD1P3DX
        port map (D=>r_gdata_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_0);

    FF_90: FD1P3DX
        port map (D=>r_gdata_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_1);

    FF_89: FD1P3DX
        port map (D=>r_gdata_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_2);

    FF_88: FD1P3DX
        port map (D=>r_gdata_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_3);

    FF_87: FD1P3DX
        port map (D=>r_gdata_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_4);

    FF_86: FD1P3DX
        port map (D=>r_gdata_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_5);

    FF_85: FD1P3DX
        port map (D=>r_gdata_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_6);

    FF_84: FD1P3DX
        port map (D=>r_gdata_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_7);

    FF_83: FD1P3DX
        port map (D=>r_gdata_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_8);

    FF_82: FD1P3DX
        port map (D=>rcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_9);

    FF_81: FD1P3DX
        port map (D=>rcount_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_0);

    FF_80: FD1P3DX
        port map (D=>rcount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_1);

    FF_79: FD1P3DX
        port map (D=>rcount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_2);

    FF_78: FD1P3DX
        port map (D=>rcount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_3);

    FF_77: FD1P3DX
        port map (D=>rcount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_4);

    FF_76: FD1P3DX
        port map (D=>rcount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_5);

    FF_75: FD1P3DX
        port map (D=>rcount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_6);

    FF_74: FD1P3DX
        port map (D=>rcount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_7);

    FF_73: FD1P3DX
        port map (D=>rcount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_8);

    FF_72: FD1P3DX
        port map (D=>rcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_9);

    FF_71: FD1S3DX
        port map (D=>w_gcount_0, CK=>RdClock, CD=>Reset, Q=>w_gcount_r0);

    FF_70: FD1S3DX
        port map (D=>w_gcount_1, CK=>RdClock, CD=>Reset, Q=>w_gcount_r1);

    FF_69: FD1S3DX
        port map (D=>w_gcount_2, CK=>RdClock, CD=>Reset, Q=>w_gcount_r2);

    FF_68: FD1S3DX
        port map (D=>w_gcount_3, CK=>RdClock, CD=>Reset, Q=>w_gcount_r3);

    FF_67: FD1S3DX
        port map (D=>w_gcount_4, CK=>RdClock, CD=>Reset, Q=>w_gcount_r4);

    FF_66: FD1S3DX
        port map (D=>w_gcount_5, CK=>RdClock, CD=>Reset, Q=>w_gcount_r5);

    FF_65: FD1S3DX
        port map (D=>w_gcount_6, CK=>RdClock, CD=>Reset, Q=>w_gcount_r6);

    FF_64: FD1S3DX
        port map (D=>r_gcount_0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w0);

    FF_63: FD1S3DX
        port map (D=>r_gcount_1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w1);

    FF_62: FD1S3DX
        port map (D=>r_gcount_2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w2);

    FF_61: FD1S3DX
        port map (D=>r_gcount_3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w3);

    FF_60: FD1S3DX
        port map (D=>r_gcount_4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w4);

    FF_59: FD1S3DX
        port map (D=>r_gcount_5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w5);

    FF_58: FD1S3DX
        port map (D=>r_gcount_6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w6);

    FF_57: FD1S3DX
        port map (D=>r_gcount_7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w7);

    FF_56: FD1S3DX
        port map (D=>r_gcount_8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w8);

    FF_55: FD1S3DX
        port map (D=>r_gcount_9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w9);

    FF_54: FD1S3DX
        port map (D=>w_gcount_r0, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r20);

    FF_53: FD1S3DX
        port map (D=>w_gcount_r1, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r21);

    FF_52: FD1S3DX
        port map (D=>w_gcount_r2, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r22);

    FF_51: FD1S3DX
        port map (D=>w_gcount_r3, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r23);

    FF_50: FD1S3DX
        port map (D=>w_gcount_r4, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r24);

    FF_49: FD1S3DX
        port map (D=>w_gcount_r5, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r25);

    FF_48: FD1S3DX
        port map (D=>w_gcount_r6, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r26);

    FF_47: FD1S3DX
        port map (D=>r_gcount_w0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w20);

    FF_46: FD1S3DX
        port map (D=>r_gcount_w1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w21);

    FF_45: FD1S3DX
        port map (D=>r_gcount_w2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w22);

    FF_44: FD1S3DX
        port map (D=>r_gcount_w3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w23);

    FF_43: FD1S3DX
        port map (D=>r_gcount_w4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w24);

    FF_42: FD1S3DX
        port map (D=>r_gcount_w5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w25);

    FF_41: FD1S3DX
        port map (D=>r_gcount_w6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w26);

    FF_40: FD1S3DX
        port map (D=>r_gcount_w7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w27);

    FF_39: FD1S3DX
        port map (D=>r_gcount_w8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w28);

    FF_38: FD1S3DX
        port map (D=>r_gcount_w9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w29);

    FF_37: FD1S3BX
        port map (D=>empty_d, CK=>RdClock, PD=>rRst, Q=>empty_i);

    FF_36: FD1S3DX
        port map (D=>full_d, CK=>WrClock, CD=>Reset, Q=>full_i);

    FF_35: FD1P3BX
        port map (D=>iae_setcount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_setcount_0);

    FF_34: FD1P3BX
        port map (D=>iae_setcount_1, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_setcount_1);

    FF_33: FD1P3DX
        port map (D=>iae_setcount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_2);

    FF_32: FD1P3BX
        port map (D=>iae_setcount_3, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_setcount_3);

    FF_31: FD1P3DX
        port map (D=>iae_setcount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_4);

    FF_30: FD1P3DX
        port map (D=>iae_setcount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_5);

    FF_29: FD1P3DX
        port map (D=>iae_setcount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_6);

    FF_28: FD1P3DX
        port map (D=>iae_setcount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_7);

    FF_27: FD1P3DX
        port map (D=>iae_setcount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_8);

    FF_26: FD1P3DX
        port map (D=>iae_setcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_9);

    FF_25: FD1P3BX
        port map (D=>iae_clrcount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_clrcount_0);

    FF_24: FD1P3DX
        port map (D=>iae_clrcount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_1);

    FF_23: FD1P3BX
        port map (D=>iae_clrcount_2, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_clrcount_2);

    FF_22: FD1P3BX
        port map (D=>iae_clrcount_3, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_clrcount_3);

    FF_21: FD1P3DX
        port map (D=>iae_clrcount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_4);

    FF_20: FD1P3DX
        port map (D=>iae_clrcount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_5);

    FF_19: FD1P3DX
        port map (D=>iae_clrcount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_6);

    FF_18: FD1P3DX
        port map (D=>iae_clrcount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_7);

    FF_17: FD1P3DX
        port map (D=>iae_clrcount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_8);

    FF_16: FD1P3DX
        port map (D=>iae_clrcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_9);

    FF_15: FD1S3BX
        port map (D=>ae_d, CK=>RdClock, PD=>rRst, Q=>ae);

    FF_14: FD1P3DX
        port map (D=>iaf_setcount_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_0);

    FF_13: FD1P3BX
        port map (D=>iaf_setcount_1, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_setcount_1);

    FF_12: FD1P3DX
        port map (D=>iaf_setcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_2);

    FF_11: FD1P3DX
        port map (D=>iaf_setcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_3);

    FF_10: FD1P3DX
        port map (D=>iaf_setcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_4);

    FF_9: FD1P3DX
        port map (D=>iaf_setcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_5);

    FF_8: FD1P3DX
        port map (D=>iaf_setcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_6);

    FF_7: FD1P3BX
        port map (D=>iaf_clrcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_clrcount_0);

    FF_6: FD1P3BX
        port map (D=>iaf_clrcount_1, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_clrcount_1);

    FF_5: FD1P3DX
        port map (D=>iaf_clrcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_2);

    FF_4: FD1P3DX
        port map (D=>iaf_clrcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_3);

    FF_3: FD1P3DX
        port map (D=>iaf_clrcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_4);

    FF_2: FD1P3DX
        port map (D=>iaf_clrcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_5);

    FF_1: FD1P3DX
        port map (D=>iaf_clrcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_6);

    FF_0: FD1S3DX
        port map (D=>af_d, CK=>WrClock, CD=>Reset, Q=>af);

    w_gctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>w_gctr_ci, S0=>open, 
            S1=>open);

    w_gctr_0: CU2
        port map (CI=>w_gctr_ci, PC0=>wcount_0, PC1=>wcount_1, CO=>co0, 
            NC0=>iwcount_0, NC1=>iwcount_1);

    w_gctr_1: CU2
        port map (CI=>co0, PC0=>wcount_2, PC1=>wcount_3, CO=>co1, 
            NC0=>iwcount_2, NC1=>iwcount_3);

    w_gctr_2: CU2
        port map (CI=>co1, PC0=>wcount_4, PC1=>wcount_5, CO=>co2, 
            NC0=>iwcount_4, NC1=>iwcount_5);

    w_gctr_3: CU2
        port map (CI=>co2, PC0=>wcount_6, PC1=>scuba_vlo, CO=>co3, 
            NC0=>iwcount_6, NC1=>open);

    r_gctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>r_gctr_ci, S0=>open, 
            S1=>open);

    r_gctr_0: CU2
        port map (CI=>r_gctr_ci, PC0=>rcount_0, PC1=>rcount_1, CO=>co0_1, 
            NC0=>ircount_0, NC1=>ircount_1);

    r_gctr_1: CU2
        port map (CI=>co0_1, PC0=>rcount_2, PC1=>rcount_3, CO=>co1_1, 
            NC0=>ircount_2, NC1=>ircount_3);

    r_gctr_2: CU2
        port map (CI=>co1_1, PC0=>rcount_4, PC1=>rcount_5, CO=>co2_1, 
            NC0=>ircount_4, NC1=>ircount_5);

    r_gctr_3: CU2
        port map (CI=>co2_1, PC0=>rcount_6, PC1=>rcount_7, CO=>co3_1, 
            NC0=>ircount_6, NC1=>ircount_7);

    r_gctr_4: CU2
        port map (CI=>co3_1, PC0=>rcount_8, PC1=>rcount_9, CO=>co4, 
            NC0=>ircount_8, NC1=>ircount_9);

    empty_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>rden_i, B0=>scuba_vlo, B1=>rden_i, 
            CI=>scuba_vlo, COUT=>cmp_ci, S0=>open, S1=>open);

    empty_cmp_0: AGEB2
        port map (A0=>rcount_0, A1=>rcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>cmp_ci, GE=>co0_2);

    empty_cmp_1: AGEB2
        port map (A0=>rcount_2, A1=>rcount_3, B0=>scuba_vlo, 
            B1=>wcount_r0, CI=>co0_2, GE=>co1_2);

    empty_cmp_2: AGEB2
        port map (A0=>rcount_4, A1=>rcount_5, B0=>wcount_r1, 
            B1=>wcount_r2, CI=>co1_2, GE=>co2_2);

    empty_cmp_3: AGEB2
        port map (A0=>rcount_6, A1=>rcount_7, B0=>w_g2b_xor_cluster_0, 
            B1=>wcount_r4, CI=>co2_2, GE=>co3_2);

    empty_cmp_4: AGEB2
        port map (A0=>rcount_8, A1=>empty_cmp_set, B0=>wcount_r5, 
            B1=>empty_cmp_clr, CI=>co3_2, GE=>empty_d_c);

    a0: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>empty_d_c, COUT=>open, S0=>empty_d, 
            S1=>open);

    full_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>wren_i, B0=>scuba_vlo, B1=>wren_i, 
            CI=>scuba_vlo, COUT=>cmp_ci_1, S0=>open, S1=>open);

    full_cmp_0: AGEB2
        port map (A0=>wcount_0, A1=>wcount_1, B0=>rcount_w3, 
            B1=>rcount_w4, CI=>cmp_ci_1, GE=>co0_3);

    full_cmp_1: AGEB2
        port map (A0=>wcount_2, A1=>wcount_3, B0=>rcount_w5, 
            B1=>r_g2b_xor_cluster_0, CI=>co0_3, GE=>co1_3);

    full_cmp_2: AGEB2
        port map (A0=>wcount_4, A1=>wcount_5, B0=>rcount_w7, 
            B1=>rcount_w8, CI=>co1_3, GE=>co2_3);

    full_cmp_3: AGEB2
        port map (A0=>full_cmp_set, A1=>scuba_vlo, B0=>full_cmp_clr, 
            B1=>scuba_vlo, CI=>co2_3, GE=>full_d_c);

    a1: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>full_d_c, COUT=>open, S0=>full_d, 
            S1=>open);

    ae_set_ctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>ae_set_ctr_ci, S0=>open, 
            S1=>open);

    ae_set_ctr_0: CU2
        port map (CI=>ae_set_ctr_ci, PC0=>ae_setcount_0, 
            PC1=>ae_setcount_1, CO=>co0_4, NC0=>iae_setcount_0, 
            NC1=>iae_setcount_1);

    ae_set_ctr_1: CU2
        port map (CI=>co0_4, PC0=>ae_setcount_2, PC1=>ae_setcount_3, 
            CO=>co1_4, NC0=>iae_setcount_2, NC1=>iae_setcount_3);

    ae_set_ctr_2: CU2
        port map (CI=>co1_4, PC0=>ae_setcount_4, PC1=>ae_setcount_5, 
            CO=>co2_4, NC0=>iae_setcount_4, NC1=>iae_setcount_5);

    ae_set_ctr_3: CU2
        port map (CI=>co2_4, PC0=>ae_setcount_6, PC1=>ae_setcount_7, 
            CO=>co3_3, NC0=>iae_setcount_6, NC1=>iae_setcount_7);

    ae_set_ctr_4: CU2
        port map (CI=>co3_3, PC0=>ae_setcount_8, PC1=>ae_setcount_9, 
            CO=>co4_1, NC0=>iae_setcount_8, NC1=>iae_setcount_9);

    ae_set_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>rden_i, B0=>scuba_vlo, B1=>rden_i, 
            CI=>scuba_vlo, COUT=>cmp_ci_2, S0=>open, S1=>open);

    ae_set_cmp_0: AGEB2
        port map (A0=>ae_setcount_0, A1=>ae_setcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>cmp_ci_2, GE=>co0_5);

    ae_set_cmp_1: AGEB2
        port map (A0=>ae_setcount_2, A1=>ae_setcount_3, B0=>scuba_vlo, 
            B1=>wcount_r0, CI=>co0_5, GE=>co1_5);

    ae_set_cmp_2: AGEB2
        port map (A0=>ae_setcount_4, A1=>ae_setcount_5, B0=>wcount_r1, 
            B1=>wcount_r2, CI=>co1_5, GE=>co2_5);

    ae_set_cmp_3: AGEB2
        port map (A0=>ae_setcount_6, A1=>ae_setcount_7, 
            B0=>w_g2b_xor_cluster_0, B1=>wcount_r4, CI=>co2_5, GE=>co3_4);

    ae_set_cmp_4: AGEB2
        port map (A0=>ae_setcount_8, A1=>ae_set_cmp_set, B0=>wcount_r5, 
            B1=>ae_set_cmp_clr, CI=>co3_4, GE=>ae_set_d_c);

    a2: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>ae_set_d_c, COUT=>open, S0=>ae_set_d, 
            S1=>open);

    ae_clr_ctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>ae_clr_ctr_ci, S0=>open, 
            S1=>open);

    ae_clr_ctr_0: CU2
        port map (CI=>ae_clr_ctr_ci, PC0=>ae_clrcount_0, 
            PC1=>ae_clrcount_1, CO=>co0_6, NC0=>iae_clrcount_0, 
            NC1=>iae_clrcount_1);

    ae_clr_ctr_1: CU2
        port map (CI=>co0_6, PC0=>ae_clrcount_2, PC1=>ae_clrcount_3, 
            CO=>co1_6, NC0=>iae_clrcount_2, NC1=>iae_clrcount_3);

    ae_clr_ctr_2: CU2
        port map (CI=>co1_6, PC0=>ae_clrcount_4, PC1=>ae_clrcount_5, 
            CO=>co2_6, NC0=>iae_clrcount_4, NC1=>iae_clrcount_5);

    ae_clr_ctr_3: CU2
        port map (CI=>co2_6, PC0=>ae_clrcount_6, PC1=>ae_clrcount_7, 
            CO=>co3_5, NC0=>iae_clrcount_6, NC1=>iae_clrcount_7);

    ae_clr_ctr_4: CU2
        port map (CI=>co3_5, PC0=>ae_clrcount_8, PC1=>ae_clrcount_9, 
            CO=>co4_2, NC0=>iae_clrcount_8, NC1=>iae_clrcount_9);

    ae_clr_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>rden_i, B0=>scuba_vlo, B1=>rden_i, 
            CI=>scuba_vlo, COUT=>cmp_ci_3, S0=>open, S1=>open);

    ae_clr_cmp_0: AGEB2
        port map (A0=>ae_clrcount_0, A1=>ae_clrcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>cmp_ci_3, GE=>co0_7);

    ae_clr_cmp_1: AGEB2
        port map (A0=>ae_clrcount_2, A1=>ae_clrcount_3, B0=>scuba_vlo, 
            B1=>wcount_r0, CI=>co0_7, GE=>co1_7);

    ae_clr_cmp_2: AGEB2
        port map (A0=>ae_clrcount_4, A1=>ae_clrcount_5, B0=>wcount_r1, 
            B1=>wcount_r2, CI=>co1_7, GE=>co2_7);

    ae_clr_cmp_3: AGEB2
        port map (A0=>ae_clrcount_6, A1=>ae_clrcount_7, 
            B0=>w_g2b_xor_cluster_0, B1=>wcount_r4, CI=>co2_7, GE=>co3_6);

    ae_clr_cmp_4: AGEB2
        port map (A0=>ae_clrcount_8, A1=>ae_clr_cmp_set, B0=>wcount_r5, 
            B1=>ae_clr_cmp_clr, CI=>co3_6, GE=>ae_clr_d_c);

    a3: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>ae_clr_d_c, COUT=>open, S0=>ae_clr_d, 
            S1=>open);

    af_set_ctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>af_set_ctr_ci, S0=>open, 
            S1=>open);

    af_set_ctr_0: CU2
        port map (CI=>af_set_ctr_ci, PC0=>af_setcount_0, 
            PC1=>af_setcount_1, CO=>co0_8, NC0=>iaf_setcount_0, 
            NC1=>iaf_setcount_1);

    af_set_ctr_1: CU2
        port map (CI=>co0_8, PC0=>af_setcount_2, PC1=>af_setcount_3, 
            CO=>co1_8, NC0=>iaf_setcount_2, NC1=>iaf_setcount_3);

    af_set_ctr_2: CU2
        port map (CI=>co1_8, PC0=>af_setcount_4, PC1=>af_setcount_5, 
            CO=>co2_8, NC0=>iaf_setcount_4, NC1=>iaf_setcount_5);

    af_set_ctr_3: CU2
        port map (CI=>co2_8, PC0=>af_setcount_6, PC1=>scuba_vlo, 
            CO=>co3_7, NC0=>iaf_setcount_6, NC1=>open);

    af_set_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>wren_i, B0=>scuba_vlo, B1=>wren_i, 
            CI=>scuba_vlo, COUT=>cmp_ci_4, S0=>open, S1=>open);

    af_set_cmp_0: AGEB2
        port map (A0=>af_setcount_0, A1=>af_setcount_1, B0=>rcount_w3, 
            B1=>rcount_w4, CI=>cmp_ci_4, GE=>co0_9);

    af_set_cmp_1: AGEB2
        port map (A0=>af_setcount_2, A1=>af_setcount_3, B0=>rcount_w5, 
            B1=>r_g2b_xor_cluster_0, CI=>co0_9, GE=>co1_9);

    af_set_cmp_2: AGEB2
        port map (A0=>af_setcount_4, A1=>af_setcount_5, B0=>rcount_w7, 
            B1=>rcount_w8, CI=>co1_9, GE=>co2_9);

    af_set_cmp_3: AGEB2
        port map (A0=>af_set_cmp_set, A1=>scuba_vlo, B0=>af_set_cmp_clr, 
            B1=>scuba_vlo, CI=>co2_9, GE=>af_set_c);

    a4: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>af_set_c, COUT=>open, S0=>af_set, 
            S1=>open);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    af_clr_ctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>af_clr_ctr_ci, S0=>open, 
            S1=>open);

    af_clr_ctr_0: CU2
        port map (CI=>af_clr_ctr_ci, PC0=>af_clrcount_0, 
            PC1=>af_clrcount_1, CO=>co0_10, NC0=>iaf_clrcount_0, 
            NC1=>iaf_clrcount_1);

    af_clr_ctr_1: CU2
        port map (CI=>co0_10, PC0=>af_clrcount_2, PC1=>af_clrcount_3, 
            CO=>co1_10, NC0=>iaf_clrcount_2, NC1=>iaf_clrcount_3);

    af_clr_ctr_2: CU2
        port map (CI=>co1_10, PC0=>af_clrcount_4, PC1=>af_clrcount_5, 
            CO=>co2_10, NC0=>iaf_clrcount_4, NC1=>iaf_clrcount_5);

    af_clr_ctr_3: CU2
        port map (CI=>co2_10, PC0=>af_clrcount_6, PC1=>scuba_vlo, 
            CO=>co3_8, NC0=>iaf_clrcount_6, NC1=>open);

    af_clr_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>wren_i, B0=>scuba_vlo, B1=>wren_i, 
            CI=>scuba_vlo, COUT=>cmp_ci_5, S0=>open, S1=>open);

    af_clr_cmp_0: AGEB2
        port map (A0=>af_clrcount_0, A1=>af_clrcount_1, B0=>rcount_w3, 
            B1=>rcount_w4, CI=>cmp_ci_5, GE=>co0_11);

    af_clr_cmp_1: AGEB2
        port map (A0=>af_clrcount_2, A1=>af_clrcount_3, B0=>rcount_w5, 
            B1=>r_g2b_xor_cluster_0, CI=>co0_11, GE=>co1_11);

    af_clr_cmp_2: AGEB2
        port map (A0=>af_clrcount_4, A1=>af_clrcount_5, B0=>rcount_w7, 
            B1=>rcount_w8, CI=>co1_11, GE=>co2_11);

    af_clr_cmp_3: AGEB2
        port map (A0=>af_clr_cmp_set, A1=>scuba_vlo, B0=>af_clr_cmp_clr, 
            B1=>scuba_vlo, CI=>co2_11, GE=>af_clr_c);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    a5: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>af_clr_c, COUT=>open, S0=>af_clr, 
            S1=>open);

    Empty <= empty_i;
    Full <= full_i;
    AlmostEmpty <= ae;
    AlmostFull <= af;
end Structure;

-- synopsys translate_off
library ecp3;
configuration Structure_CON of fifo_512x64x8 is
    for Structure
        for all:AGEB2 use entity ecp3.AGEB2(V); end for;
        for all:AND2 use entity ecp3.AND2(V); end for;
        for all:CU2 use entity ecp3.CU2(V); end for;
        for all:FADD2B use entity ecp3.FADD2B(V); end for;
        for all:FD1P3BX use entity ecp3.FD1P3BX(V); end for;
        for all:FD1P3DX use entity ecp3.FD1P3DX(V); end for;
        for all:FD1S3BX use entity ecp3.FD1S3BX(V); end for;
        for all:FD1S3DX use entity ecp3.FD1S3DX(V); end for;
        for all:INV use entity ecp3.INV(V); end for;
        for all:OR2 use entity ecp3.OR2(V); end for;
        for all:ROM16X1A use entity ecp3.ROM16X1A(V); end for;
        for all:VHI use entity ecp3.VHI(V); end for;
        for all:VLO use entity ecp3.VLO(V); end for;
        for all:XOR2 use entity ecp3.XOR2(V); end for;
        for all:PDPW16KC use entity ecp3.PDPW16KC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
