-- VHDL netlist generated by SCUBA Diamond_1.3_Production (92)
-- Module  Version: 5.4
--/opt/lattice/diamond/1.3/ispfpga/bin/lin/scuba -w -lang vhdl -synth synplify -bus_exp 7 -bb -arch ep5c00 -type ebfifo -depth 1024 -width 18 -depth 1024 -rdata_width 9 -no_enable -pe -1 -pf -1 -e 

-- Mon Dec  5 18:27:25 2011

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp3;
use ecp3.components.all;
-- synopsys translate_on

entity fifo_1024x16x8 is
    port (
        Data: in  std_logic_vector(17 downto 0); 
        WrClock: in  std_logic; 
        RdClock: in  std_logic; 
        WrEn: in  std_logic; 
        RdEn: in  std_logic; 
        Reset: in  std_logic; 
        RPReset: in  std_logic; 
        Q: out  std_logic_vector(8 downto 0); 
        Empty: out  std_logic; 
        Full: out  std_logic);
end fifo_1024x16x8;

architecture Structure of fifo_1024x16x8 is

    -- internal signal declarations
    signal invout_1: std_logic;
    signal invout_0: std_logic;
    signal w_g2b_xor_cluster_2: std_logic;
    signal w_g2b_xor_cluster_1: std_logic;
    signal r_g2b_xor_cluster_2_1: std_logic;
    signal rcount_w0: std_logic;
    signal r_g2b_xor_cluster_2: std_logic;
    signal r_g2b_xor_cluster_1: std_logic;
    signal w_gdata_0: std_logic;
    signal w_gdata_1: std_logic;
    signal w_gdata_2: std_logic;
    signal w_gdata_3: std_logic;
    signal w_gdata_4: std_logic;
    signal w_gdata_5: std_logic;
    signal w_gdata_6: std_logic;
    signal w_gdata_7: std_logic;
    signal w_gdata_8: std_logic;
    signal w_gdata_9: std_logic;
    signal wptr_0: std_logic;
    signal wptr_1: std_logic;
    signal wptr_2: std_logic;
    signal wptr_3: std_logic;
    signal wptr_4: std_logic;
    signal wptr_5: std_logic;
    signal wptr_6: std_logic;
    signal wptr_7: std_logic;
    signal wptr_8: std_logic;
    signal wptr_9: std_logic;
    signal wptr_10: std_logic;
    signal r_gdata_0: std_logic;
    signal r_gdata_1: std_logic;
    signal r_gdata_2: std_logic;
    signal r_gdata_3: std_logic;
    signal r_gdata_4: std_logic;
    signal r_gdata_5: std_logic;
    signal r_gdata_6: std_logic;
    signal r_gdata_7: std_logic;
    signal r_gdata_8: std_logic;
    signal r_gdata_9: std_logic;
    signal r_gdata_10: std_logic;
    signal rptr_0: std_logic;
    signal rptr_1: std_logic;
    signal rptr_2: std_logic;
    signal rptr_3: std_logic;
    signal rptr_4: std_logic;
    signal rptr_5: std_logic;
    signal rptr_6: std_logic;
    signal rptr_7: std_logic;
    signal rptr_8: std_logic;
    signal rptr_9: std_logic;
    signal rptr_10: std_logic;
    signal rptr_11: std_logic;
    signal w_gcount_0: std_logic;
    signal w_gcount_1: std_logic;
    signal w_gcount_2: std_logic;
    signal w_gcount_3: std_logic;
    signal w_gcount_4: std_logic;
    signal w_gcount_5: std_logic;
    signal w_gcount_6: std_logic;
    signal w_gcount_7: std_logic;
    signal w_gcount_8: std_logic;
    signal w_gcount_9: std_logic;
    signal w_gcount_10: std_logic;
    signal r_gcount_0: std_logic;
    signal r_gcount_1: std_logic;
    signal r_gcount_2: std_logic;
    signal r_gcount_3: std_logic;
    signal r_gcount_4: std_logic;
    signal r_gcount_5: std_logic;
    signal r_gcount_6: std_logic;
    signal r_gcount_7: std_logic;
    signal r_gcount_8: std_logic;
    signal r_gcount_9: std_logic;
    signal r_gcount_10: std_logic;
    signal r_gcount_11: std_logic;
    signal w_gcount_r20: std_logic;
    signal w_gcount_r0: std_logic;
    signal w_gcount_r21: std_logic;
    signal w_gcount_r1: std_logic;
    signal w_gcount_r22: std_logic;
    signal w_gcount_r2: std_logic;
    signal w_gcount_r23: std_logic;
    signal w_gcount_r3: std_logic;
    signal w_gcount_r24: std_logic;
    signal w_gcount_r4: std_logic;
    signal w_gcount_r25: std_logic;
    signal w_gcount_r5: std_logic;
    signal w_gcount_r26: std_logic;
    signal w_gcount_r6: std_logic;
    signal w_gcount_r27: std_logic;
    signal w_gcount_r7: std_logic;
    signal w_gcount_r28: std_logic;
    signal w_gcount_r8: std_logic;
    signal w_gcount_r29: std_logic;
    signal w_gcount_r9: std_logic;
    signal w_gcount_r210: std_logic;
    signal w_gcount_r10: std_logic;
    signal r_gcount_w20: std_logic;
    signal r_gcount_w0: std_logic;
    signal r_gcount_w21: std_logic;
    signal r_gcount_w1: std_logic;
    signal r_gcount_w22: std_logic;
    signal r_gcount_w2: std_logic;
    signal r_gcount_w23: std_logic;
    signal r_gcount_w3: std_logic;
    signal r_gcount_w24: std_logic;
    signal r_gcount_w4: std_logic;
    signal r_gcount_w25: std_logic;
    signal r_gcount_w5: std_logic;
    signal r_gcount_w26: std_logic;
    signal r_gcount_w6: std_logic;
    signal r_gcount_w27: std_logic;
    signal r_gcount_w7: std_logic;
    signal r_gcount_w28: std_logic;
    signal r_gcount_w8: std_logic;
    signal r_gcount_w29: std_logic;
    signal r_gcount_w9: std_logic;
    signal r_gcount_w210: std_logic;
    signal r_gcount_w10: std_logic;
    signal r_gcount_w211: std_logic;
    signal r_gcount_w11: std_logic;
    signal empty_i: std_logic;
    signal rRst: std_logic;
    signal full_i: std_logic;
    signal iwcount_0: std_logic;
    signal iwcount_1: std_logic;
    signal w_gctr_ci: std_logic;
    signal iwcount_2: std_logic;
    signal iwcount_3: std_logic;
    signal co0: std_logic;
    signal iwcount_4: std_logic;
    signal iwcount_5: std_logic;
    signal co1: std_logic;
    signal iwcount_6: std_logic;
    signal iwcount_7: std_logic;
    signal co2: std_logic;
    signal iwcount_8: std_logic;
    signal iwcount_9: std_logic;
    signal co3: std_logic;
    signal iwcount_10: std_logic;
    signal co5: std_logic;
    signal wcount_10: std_logic;
    signal co4: std_logic;
    signal scuba_vhi: std_logic;
    signal ircount_0: std_logic;
    signal ircount_1: std_logic;
    signal r_gctr_ci: std_logic;
    signal ircount_2: std_logic;
    signal ircount_3: std_logic;
    signal co0_1: std_logic;
    signal ircount_4: std_logic;
    signal ircount_5: std_logic;
    signal co1_1: std_logic;
    signal ircount_6: std_logic;
    signal ircount_7: std_logic;
    signal co2_1: std_logic;
    signal ircount_8: std_logic;
    signal ircount_9: std_logic;
    signal co3_1: std_logic;
    signal ircount_10: std_logic;
    signal ircount_11: std_logic;
    signal co5_1: std_logic;
    signal rcount_11: std_logic;
    signal co4_1: std_logic;
    signal rden_i: std_logic;
    signal cmp_ci: std_logic;
    signal wcount_r0: std_logic;
    signal rcount_0: std_logic;
    signal rcount_1: std_logic;
    signal co0_2: std_logic;
    signal wcount_r1: std_logic;
    signal wcount_r2: std_logic;
    signal rcount_2: std_logic;
    signal rcount_3: std_logic;
    signal co1_2: std_logic;
    signal wcount_r3: std_logic;
    signal wcount_r4: std_logic;
    signal rcount_4: std_logic;
    signal rcount_5: std_logic;
    signal co2_2: std_logic;
    signal wcount_r5: std_logic;
    signal wcount_r6: std_logic;
    signal rcount_6: std_logic;
    signal rcount_7: std_logic;
    signal co3_2: std_logic;
    signal w_g2b_xor_cluster_0: std_logic;
    signal wcount_r8: std_logic;
    signal rcount_8: std_logic;
    signal rcount_9: std_logic;
    signal co4_2: std_logic;
    signal wcount_r9: std_logic;
    signal empty_cmp_clr: std_logic;
    signal rcount_10: std_logic;
    signal empty_cmp_set: std_logic;
    signal empty_d: std_logic;
    signal empty_d_c: std_logic;
    signal wren_i: std_logic;
    signal cmp_ci_1: std_logic;
    signal rcount_w1: std_logic;
    signal rcount_w2: std_logic;
    signal wcount_0: std_logic;
    signal wcount_1: std_logic;
    signal co0_3: std_logic;
    signal rcount_w3: std_logic;
    signal rcount_w4: std_logic;
    signal wcount_2: std_logic;
    signal wcount_3: std_logic;
    signal co1_3: std_logic;
    signal rcount_w5: std_logic;
    signal rcount_w6: std_logic;
    signal wcount_4: std_logic;
    signal wcount_5: std_logic;
    signal co2_3: std_logic;
    signal rcount_w7: std_logic;
    signal r_g2b_xor_cluster_0: std_logic;
    signal wcount_6: std_logic;
    signal wcount_7: std_logic;
    signal co3_3: std_logic;
    signal rcount_w9: std_logic;
    signal rcount_w10: std_logic;
    signal wcount_8: std_logic;
    signal wcount_9: std_logic;
    signal co4_3: std_logic;
    signal full_cmp_clr: std_logic;
    signal full_cmp_set: std_logic;
    signal full_d: std_logic;
    signal full_d_c: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component AGEB2
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; GE: out  std_logic);
    end component;
    component AND2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component CU2
        port (CI: in  std_logic; PC0: in  std_logic; PC1: in  std_logic; 
            CO: out  std_logic; NC0: out  std_logic; NC1: out  std_logic);
    end component;
    component FADD2B
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; COUT: out  std_logic; 
            S0: out  std_logic; S1: out  std_logic);
    end component;
    component FD1P3BX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            PD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1S3BX
        port (D: in  std_logic; CK: in  std_logic; PD: in  std_logic; 
            Q: out  std_logic);
    end component;
    component FD1S3DX
        port (D: in  std_logic; CK: in  std_logic; CD: in  std_logic; 
            Q: out  std_logic);
    end component;
    component INV
        port (A: in  std_logic; Z: out  std_logic);
    end component;
    component OR2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component ROM16X1A
        generic (INITVAL : in std_logic_vector(15 downto 0));
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component XOR2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component DP16KC
        generic (GSR : in String; WRITEMODE_B : in String; 
                WRITEMODE_A : in String; CSDECODE_B : in String; 
                CSDECODE_A : in String; REGMODE_B : in String; 
                REGMODE_A : in String; DATA_WIDTH_B : in Integer; 
                DATA_WIDTH_A : in Integer);
        port (DIA0: in  std_logic; DIA1: in  std_logic; 
            DIA2: in  std_logic; DIA3: in  std_logic; 
            DIA4: in  std_logic; DIA5: in  std_logic; 
            DIA6: in  std_logic; DIA7: in  std_logic; 
            DIA8: in  std_logic; DIA9: in  std_logic; 
            DIA10: in  std_logic; DIA11: in  std_logic; 
            DIA12: in  std_logic; DIA13: in  std_logic; 
            DIA14: in  std_logic; DIA15: in  std_logic; 
            DIA16: in  std_logic; DIA17: in  std_logic; 
            ADA0: in  std_logic; ADA1: in  std_logic; 
            ADA2: in  std_logic; ADA3: in  std_logic; 
            ADA4: in  std_logic; ADA5: in  std_logic; 
            ADA6: in  std_logic; ADA7: in  std_logic; 
            ADA8: in  std_logic; ADA9: in  std_logic; 
            ADA10: in  std_logic; ADA11: in  std_logic; 
            ADA12: in  std_logic; ADA13: in  std_logic; 
            CEA: in  std_logic; CLKA: in  std_logic; OCEA: in  std_logic; 
            WEA: in  std_logic; CSA0: in  std_logic; CSA1: in  std_logic; 
            CSA2: in  std_logic; RSTA: in  std_logic; 
            DIB0: in  std_logic; DIB1: in  std_logic; 
            DIB2: in  std_logic; DIB3: in  std_logic; 
            DIB4: in  std_logic; DIB5: in  std_logic; 
            DIB6: in  std_logic; DIB7: in  std_logic; 
            DIB8: in  std_logic; DIB9: in  std_logic; 
            DIB10: in  std_logic; DIB11: in  std_logic; 
            DIB12: in  std_logic; DIB13: in  std_logic; 
            DIB14: in  std_logic; DIB15: in  std_logic; 
            DIB16: in  std_logic; DIB17: in  std_logic; 
            ADB0: in  std_logic; ADB1: in  std_logic; 
            ADB2: in  std_logic; ADB3: in  std_logic; 
            ADB4: in  std_logic; ADB5: in  std_logic; 
            ADB6: in  std_logic; ADB7: in  std_logic; 
            ADB8: in  std_logic; ADB9: in  std_logic; 
            ADB10: in  std_logic; ADB11: in  std_logic; 
            ADB12: in  std_logic; ADB13: in  std_logic; 
            CEB: in  std_logic; CLKB: in  std_logic; OCEB: in  std_logic; 
            WEB: in  std_logic; CSB0: in  std_logic; CSB1: in  std_logic; 
            CSB2: in  std_logic; RSTB: in  std_logic; 
            DOA0: out  std_logic; DOA1: out  std_logic; 
            DOA2: out  std_logic; DOA3: out  std_logic; 
            DOA4: out  std_logic; DOA5: out  std_logic; 
            DOA6: out  std_logic; DOA7: out  std_logic; 
            DOA8: out  std_logic; DOA9: out  std_logic; 
            DOA10: out  std_logic; DOA11: out  std_logic; 
            DOA12: out  std_logic; DOA13: out  std_logic; 
            DOA14: out  std_logic; DOA15: out  std_logic; 
            DOA16: out  std_logic; DOA17: out  std_logic; 
            DOB0: out  std_logic; DOB1: out  std_logic; 
            DOB2: out  std_logic; DOB3: out  std_logic; 
            DOB4: out  std_logic; DOB5: out  std_logic; 
            DOB6: out  std_logic; DOB7: out  std_logic; 
            DOB8: out  std_logic; DOB9: out  std_logic; 
            DOB10: out  std_logic; DOB11: out  std_logic; 
            DOB12: out  std_logic; DOB13: out  std_logic; 
            DOB14: out  std_logic; DOB15: out  std_logic; 
            DOB16: out  std_logic; DOB17: out  std_logic);
    end component;
    attribute MEM_LPC_FILE : string; 
    attribute MEM_INIT_FILE : string; 
    attribute RESETMODE : string; 
    attribute GSR : string; 
    attribute MEM_LPC_FILE of pdp_ram_0_0_0 : label is "fifo_1024x16x8.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_0_0 : label is "";
    attribute RESETMODE of pdp_ram_0_0_0 : label is "SYNC";
    attribute GSR of FF_116 : label is "ENABLED";
    attribute GSR of FF_115 : label is "ENABLED";
    attribute GSR of FF_114 : label is "ENABLED";
    attribute GSR of FF_113 : label is "ENABLED";
    attribute GSR of FF_112 : label is "ENABLED";
    attribute GSR of FF_111 : label is "ENABLED";
    attribute GSR of FF_110 : label is "ENABLED";
    attribute GSR of FF_109 : label is "ENABLED";
    attribute GSR of FF_108 : label is "ENABLED";
    attribute GSR of FF_107 : label is "ENABLED";
    attribute GSR of FF_106 : label is "ENABLED";
    attribute GSR of FF_105 : label is "ENABLED";
    attribute GSR of FF_104 : label is "ENABLED";
    attribute GSR of FF_103 : label is "ENABLED";
    attribute GSR of FF_102 : label is "ENABLED";
    attribute GSR of FF_101 : label is "ENABLED";
    attribute GSR of FF_100 : label is "ENABLED";
    attribute GSR of FF_99 : label is "ENABLED";
    attribute GSR of FF_98 : label is "ENABLED";
    attribute GSR of FF_97 : label is "ENABLED";
    attribute GSR of FF_96 : label is "ENABLED";
    attribute GSR of FF_95 : label is "ENABLED";
    attribute GSR of FF_94 : label is "ENABLED";
    attribute GSR of FF_93 : label is "ENABLED";
    attribute GSR of FF_92 : label is "ENABLED";
    attribute GSR of FF_91 : label is "ENABLED";
    attribute GSR of FF_90 : label is "ENABLED";
    attribute GSR of FF_89 : label is "ENABLED";
    attribute GSR of FF_88 : label is "ENABLED";
    attribute GSR of FF_87 : label is "ENABLED";
    attribute GSR of FF_86 : label is "ENABLED";
    attribute GSR of FF_85 : label is "ENABLED";
    attribute GSR of FF_84 : label is "ENABLED";
    attribute GSR of FF_83 : label is "ENABLED";
    attribute GSR of FF_82 : label is "ENABLED";
    attribute GSR of FF_81 : label is "ENABLED";
    attribute GSR of FF_80 : label is "ENABLED";
    attribute GSR of FF_79 : label is "ENABLED";
    attribute GSR of FF_78 : label is "ENABLED";
    attribute GSR of FF_77 : label is "ENABLED";
    attribute GSR of FF_76 : label is "ENABLED";
    attribute GSR of FF_75 : label is "ENABLED";
    attribute GSR of FF_74 : label is "ENABLED";
    attribute GSR of FF_73 : label is "ENABLED";
    attribute GSR of FF_72 : label is "ENABLED";
    attribute GSR of FF_71 : label is "ENABLED";
    attribute GSR of FF_70 : label is "ENABLED";
    attribute GSR of FF_69 : label is "ENABLED";
    attribute GSR of FF_68 : label is "ENABLED";
    attribute GSR of FF_67 : label is "ENABLED";
    attribute GSR of FF_66 : label is "ENABLED";
    attribute GSR of FF_65 : label is "ENABLED";
    attribute GSR of FF_64 : label is "ENABLED";
    attribute GSR of FF_63 : label is "ENABLED";
    attribute GSR of FF_62 : label is "ENABLED";
    attribute GSR of FF_61 : label is "ENABLED";
    attribute GSR of FF_60 : label is "ENABLED";
    attribute GSR of FF_59 : label is "ENABLED";
    attribute GSR of FF_58 : label is "ENABLED";
    attribute GSR of FF_57 : label is "ENABLED";
    attribute GSR of FF_56 : label is "ENABLED";
    attribute GSR of FF_55 : label is "ENABLED";
    attribute GSR of FF_54 : label is "ENABLED";
    attribute GSR of FF_53 : label is "ENABLED";
    attribute GSR of FF_52 : label is "ENABLED";
    attribute GSR of FF_51 : label is "ENABLED";
    attribute GSR of FF_50 : label is "ENABLED";
    attribute GSR of FF_49 : label is "ENABLED";
    attribute GSR of FF_48 : label is "ENABLED";
    attribute GSR of FF_47 : label is "ENABLED";
    attribute GSR of FF_46 : label is "ENABLED";
    attribute GSR of FF_45 : label is "ENABLED";
    attribute GSR of FF_44 : label is "ENABLED";
    attribute GSR of FF_43 : label is "ENABLED";
    attribute GSR of FF_42 : label is "ENABLED";
    attribute GSR of FF_41 : label is "ENABLED";
    attribute GSR of FF_40 : label is "ENABLED";
    attribute GSR of FF_39 : label is "ENABLED";
    attribute GSR of FF_38 : label is "ENABLED";
    attribute GSR of FF_37 : label is "ENABLED";
    attribute GSR of FF_36 : label is "ENABLED";
    attribute GSR of FF_35 : label is "ENABLED";
    attribute GSR of FF_34 : label is "ENABLED";
    attribute GSR of FF_33 : label is "ENABLED";
    attribute GSR of FF_32 : label is "ENABLED";
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;

begin
    -- component instantiation statements
    AND2_t23: AND2
        port map (A=>WrEn, B=>invout_1, Z=>wren_i);

    INV_1: INV
        port map (A=>full_i, Z=>invout_1);

    AND2_t22: AND2
        port map (A=>RdEn, B=>invout_0, Z=>rden_i);

    INV_0: INV
        port map (A=>empty_i, Z=>invout_0);

    OR2_t21: OR2
        port map (A=>Reset, B=>RPReset, Z=>rRst);

    XOR2_t20: XOR2
        port map (A=>wcount_0, B=>wcount_1, Z=>w_gdata_0);

    XOR2_t19: XOR2
        port map (A=>wcount_1, B=>wcount_2, Z=>w_gdata_1);

    XOR2_t18: XOR2
        port map (A=>wcount_2, B=>wcount_3, Z=>w_gdata_2);

    XOR2_t17: XOR2
        port map (A=>wcount_3, B=>wcount_4, Z=>w_gdata_3);

    XOR2_t16: XOR2
        port map (A=>wcount_4, B=>wcount_5, Z=>w_gdata_4);

    XOR2_t15: XOR2
        port map (A=>wcount_5, B=>wcount_6, Z=>w_gdata_5);

    XOR2_t14: XOR2
        port map (A=>wcount_6, B=>wcount_7, Z=>w_gdata_6);

    XOR2_t13: XOR2
        port map (A=>wcount_7, B=>wcount_8, Z=>w_gdata_7);

    XOR2_t12: XOR2
        port map (A=>wcount_8, B=>wcount_9, Z=>w_gdata_8);

    XOR2_t11: XOR2
        port map (A=>wcount_9, B=>wcount_10, Z=>w_gdata_9);

    XOR2_t10: XOR2
        port map (A=>rcount_0, B=>rcount_1, Z=>r_gdata_0);

    XOR2_t9: XOR2
        port map (A=>rcount_1, B=>rcount_2, Z=>r_gdata_1);

    XOR2_t8: XOR2
        port map (A=>rcount_2, B=>rcount_3, Z=>r_gdata_2);

    XOR2_t7: XOR2
        port map (A=>rcount_3, B=>rcount_4, Z=>r_gdata_3);

    XOR2_t6: XOR2
        port map (A=>rcount_4, B=>rcount_5, Z=>r_gdata_4);

    XOR2_t5: XOR2
        port map (A=>rcount_5, B=>rcount_6, Z=>r_gdata_5);

    XOR2_t4: XOR2
        port map (A=>rcount_6, B=>rcount_7, Z=>r_gdata_6);

    XOR2_t3: XOR2
        port map (A=>rcount_7, B=>rcount_8, Z=>r_gdata_7);

    XOR2_t2: XOR2
        port map (A=>rcount_8, B=>rcount_9, Z=>r_gdata_8);

    XOR2_t1: XOR2
        port map (A=>rcount_9, B=>rcount_10, Z=>r_gdata_9);

    XOR2_t0: XOR2
        port map (A=>rcount_10, B=>rcount_11, Z=>r_gdata_10);

    LUT4_29: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r27, AD2=>w_gcount_r28, 
            AD1=>w_gcount_r29, AD0=>w_gcount_r210, 
            DO0=>w_g2b_xor_cluster_0);

    LUT4_28: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r23, AD2=>w_gcount_r24, 
            AD1=>w_gcount_r25, AD0=>w_gcount_r26, 
            DO0=>w_g2b_xor_cluster_1);

    LUT4_27: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r29, AD2=>w_gcount_r210, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>wcount_r9);

    LUT4_26: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r28, AD2=>w_gcount_r29, 
            AD1=>w_gcount_r210, AD0=>scuba_vlo, DO0=>wcount_r8);

    LUT4_25: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r26, AD2=>w_gcount_r27, 
            AD1=>w_gcount_r28, AD0=>wcount_r9, DO0=>wcount_r6);

    LUT4_24: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r25, AD2=>w_gcount_r26, 
            AD1=>w_gcount_r27, AD0=>wcount_r8, DO0=>wcount_r5);

    LUT4_23: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r24, AD2=>w_gcount_r25, 
            AD1=>w_gcount_r26, AD0=>w_g2b_xor_cluster_0, DO0=>wcount_r4);

    LUT4_22: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>scuba_vlo, AD0=>scuba_vlo, DO0=>wcount_r3);

    LUT4_21: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_gcount_r22, AD0=>scuba_vlo, DO0=>wcount_r2);

    LUT4_20: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_gcount_r21, AD0=>w_gcount_r22, DO0=>wcount_r1);

    LUT4_19: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r20, AD2=>w_gcount_r21, 
            AD1=>w_gcount_r22, AD0=>scuba_vlo, DO0=>w_g2b_xor_cluster_2);

    LUT4_18: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_g2b_xor_cluster_2, AD0=>scuba_vlo, DO0=>wcount_r0);

    LUT4_17: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w28, AD2=>r_gcount_w29, 
            AD1=>r_gcount_w210, AD0=>r_gcount_w211, 
            DO0=>r_g2b_xor_cluster_0);

    LUT4_16: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w24, AD2=>r_gcount_w25, 
            AD1=>r_gcount_w26, AD0=>r_gcount_w27, 
            DO0=>r_g2b_xor_cluster_1);

    LUT4_15: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w20, AD2=>r_gcount_w21, 
            AD1=>r_gcount_w22, AD0=>r_gcount_w23, 
            DO0=>r_g2b_xor_cluster_2);

    LUT4_14: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w210, AD2=>r_gcount_w211, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>rcount_w10);

    LUT4_13: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w29, AD2=>r_gcount_w210, 
            AD1=>r_gcount_w211, AD0=>scuba_vlo, DO0=>rcount_w9);

    LUT4_12: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w27, AD2=>r_gcount_w28, 
            AD1=>r_gcount_w29, AD0=>rcount_w10, DO0=>rcount_w7);

    LUT4_11: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w26, AD2=>r_gcount_w27, 
            AD1=>r_gcount_w28, AD0=>rcount_w9, DO0=>rcount_w6);

    LUT4_10: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w25, AD2=>r_gcount_w26, 
            AD1=>r_gcount_w27, AD0=>r_g2b_xor_cluster_0, DO0=>rcount_w5);

    LUT4_9: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>scuba_vlo, AD0=>scuba_vlo, DO0=>rcount_w4);

    LUT4_8: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w23, AD0=>scuba_vlo, DO0=>rcount_w3);

    LUT4_7: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w22, AD0=>r_gcount_w23, DO0=>rcount_w2);

    LUT4_6: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w21, AD2=>r_gcount_w22, 
            AD1=>r_gcount_w23, AD0=>scuba_vlo, 
            DO0=>r_g2b_xor_cluster_2_1);

    LUT4_5: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_g2b_xor_cluster_2_1, AD0=>scuba_vlo, DO0=>rcount_w1);

    LUT4_4: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_g2b_xor_cluster_2, AD0=>scuba_vlo, DO0=>rcount_w0);

    LUT4_3: ROM16X1A
        generic map (initval=> X"0410")
        port map (AD3=>rptr_11, AD2=>rcount_11, AD1=>w_gcount_r210, 
            AD0=>scuba_vlo, DO0=>empty_cmp_set);

    LUT4_2: ROM16X1A
        generic map (initval=> X"1004")
        port map (AD3=>rptr_11, AD2=>rcount_11, AD1=>w_gcount_r210, 
            AD0=>scuba_vlo, DO0=>empty_cmp_clr);

    LUT4_1: ROM16X1A
        generic map (initval=> X"0140")
        port map (AD3=>wptr_10, AD2=>wcount_10, AD1=>r_gcount_w211, 
            AD0=>scuba_vlo, DO0=>full_cmp_set);

    LUT4_0: ROM16X1A
        generic map (initval=> X"4001")
        port map (AD3=>wptr_10, AD2=>wcount_10, AD1=>r_gcount_w211, 
            AD0=>scuba_vlo, DO0=>full_cmp_clr);

    pdp_ram_0_0_0: DP16KC
        generic map (CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", 
        WRITEMODE_B=> "NORMAL", WRITEMODE_A=> "NORMAL", GSR=> "DISABLED", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  9, 
        DATA_WIDTH_A=>  18)
        port map (DIA0=>Data(0), DIA1=>Data(1), DIA2=>Data(2), 
            DIA3=>Data(3), DIA4=>Data(4), DIA5=>Data(5), DIA6=>Data(6), 
            DIA7=>Data(7), DIA8=>Data(8), DIA9=>Data(9), DIA10=>Data(10), 
            DIA11=>Data(11), DIA12=>Data(12), DIA13=>Data(13), 
            DIA14=>Data(14), DIA15=>Data(15), DIA16=>Data(16), 
            DIA17=>Data(17), ADA0=>scuba_vhi, ADA1=>scuba_vhi, 
            ADA2=>scuba_vlo, ADA3=>scuba_vlo, ADA4=>wptr_0, ADA5=>wptr_1, 
            ADA6=>wptr_2, ADA7=>wptr_3, ADA8=>wptr_4, ADA9=>wptr_5, 
            ADA10=>wptr_6, ADA11=>wptr_7, ADA12=>wptr_8, ADA13=>wptr_9, 
            CEA=>wren_i, CLKA=>WrClock, OCEA=>wren_i, WEA=>scuba_vhi, 
            CSA0=>scuba_vlo, CSA1=>scuba_vlo, CSA2=>scuba_vlo, 
            RSTA=>Reset, DIB0=>scuba_vlo, DIB1=>scuba_vlo, 
            DIB2=>scuba_vlo, DIB3=>scuba_vlo, DIB4=>scuba_vlo, 
            DIB5=>scuba_vlo, DIB6=>scuba_vlo, DIB7=>scuba_vlo, 
            DIB8=>scuba_vlo, DIB9=>scuba_vlo, DIB10=>scuba_vlo, 
            DIB11=>scuba_vlo, DIB12=>scuba_vlo, DIB13=>scuba_vlo, 
            DIB14=>scuba_vlo, DIB15=>scuba_vlo, DIB16=>scuba_vlo, 
            DIB17=>scuba_vlo, ADB0=>scuba_vlo, ADB1=>scuba_vlo, 
            ADB2=>scuba_vlo, ADB3=>rptr_0, ADB4=>rptr_1, ADB5=>rptr_2, 
            ADB6=>rptr_3, ADB7=>rptr_4, ADB8=>rptr_5, ADB9=>rptr_6, 
            ADB10=>rptr_7, ADB11=>rptr_8, ADB12=>rptr_9, ADB13=>rptr_10, 
            CEB=>rden_i, CLKB=>RdClock, OCEB=>rden_i, WEB=>scuba_vlo, 
            CSB0=>scuba_vlo, CSB1=>scuba_vlo, CSB2=>scuba_vlo, 
            RSTB=>Reset, DOA0=>open, DOA1=>open, DOA2=>open, DOA3=>open, 
            DOA4=>open, DOA5=>open, DOA6=>open, DOA7=>open, DOA8=>open, 
            DOA9=>open, DOA10=>open, DOA11=>open, DOA12=>open, 
            DOA13=>open, DOA14=>open, DOA15=>open, DOA16=>open, 
            DOA17=>open, DOB0=>Q(0), DOB1=>Q(1), DOB2=>Q(2), DOB3=>Q(3), 
            DOB4=>Q(4), DOB5=>Q(5), DOB6=>Q(6), DOB7=>Q(7), DOB8=>Q(8), 
            DOB9=>open, DOB10=>open, DOB11=>open, DOB12=>open, 
            DOB13=>open, DOB14=>open, DOB15=>open, DOB16=>open, 
            DOB17=>open);

    FF_116: FD1P3BX
        port map (D=>iwcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>wcount_0);

    FF_115: FD1P3DX
        port map (D=>iwcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_1);

    FF_114: FD1P3DX
        port map (D=>iwcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_2);

    FF_113: FD1P3DX
        port map (D=>iwcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_3);

    FF_112: FD1P3DX
        port map (D=>iwcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_4);

    FF_111: FD1P3DX
        port map (D=>iwcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_5);

    FF_110: FD1P3DX
        port map (D=>iwcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_6);

    FF_109: FD1P3DX
        port map (D=>iwcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_7);

    FF_108: FD1P3DX
        port map (D=>iwcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_8);

    FF_107: FD1P3DX
        port map (D=>iwcount_9, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_9);

    FF_106: FD1P3DX
        port map (D=>iwcount_10, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_10);

    FF_105: FD1P3DX
        port map (D=>w_gdata_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_0);

    FF_104: FD1P3DX
        port map (D=>w_gdata_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_1);

    FF_103: FD1P3DX
        port map (D=>w_gdata_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_2);

    FF_102: FD1P3DX
        port map (D=>w_gdata_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_3);

    FF_101: FD1P3DX
        port map (D=>w_gdata_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_4);

    FF_100: FD1P3DX
        port map (D=>w_gdata_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_5);

    FF_99: FD1P3DX
        port map (D=>w_gdata_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_6);

    FF_98: FD1P3DX
        port map (D=>w_gdata_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_7);

    FF_97: FD1P3DX
        port map (D=>w_gdata_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_8);

    FF_96: FD1P3DX
        port map (D=>w_gdata_9, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_9);

    FF_95: FD1P3DX
        port map (D=>wcount_10, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_10);

    FF_94: FD1P3DX
        port map (D=>wcount_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_0);

    FF_93: FD1P3DX
        port map (D=>wcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_1);

    FF_92: FD1P3DX
        port map (D=>wcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_2);

    FF_91: FD1P3DX
        port map (D=>wcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_3);

    FF_90: FD1P3DX
        port map (D=>wcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_4);

    FF_89: FD1P3DX
        port map (D=>wcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_5);

    FF_88: FD1P3DX
        port map (D=>wcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_6);

    FF_87: FD1P3DX
        port map (D=>wcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_7);

    FF_86: FD1P3DX
        port map (D=>wcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_8);

    FF_85: FD1P3DX
        port map (D=>wcount_9, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_9);

    FF_84: FD1P3DX
        port map (D=>wcount_10, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_10);

    FF_83: FD1P3BX
        port map (D=>ircount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>rcount_0);

    FF_82: FD1P3DX
        port map (D=>ircount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_1);

    FF_81: FD1P3DX
        port map (D=>ircount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_2);

    FF_80: FD1P3DX
        port map (D=>ircount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_3);

    FF_79: FD1P3DX
        port map (D=>ircount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_4);

    FF_78: FD1P3DX
        port map (D=>ircount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_5);

    FF_77: FD1P3DX
        port map (D=>ircount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_6);

    FF_76: FD1P3DX
        port map (D=>ircount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_7);

    FF_75: FD1P3DX
        port map (D=>ircount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_8);

    FF_74: FD1P3DX
        port map (D=>ircount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_9);

    FF_73: FD1P3DX
        port map (D=>ircount_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_10);

    FF_72: FD1P3DX
        port map (D=>ircount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_11);

    FF_71: FD1P3DX
        port map (D=>r_gdata_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_0);

    FF_70: FD1P3DX
        port map (D=>r_gdata_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_1);

    FF_69: FD1P3DX
        port map (D=>r_gdata_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_2);

    FF_68: FD1P3DX
        port map (D=>r_gdata_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_3);

    FF_67: FD1P3DX
        port map (D=>r_gdata_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_4);

    FF_66: FD1P3DX
        port map (D=>r_gdata_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_5);

    FF_65: FD1P3DX
        port map (D=>r_gdata_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_6);

    FF_64: FD1P3DX
        port map (D=>r_gdata_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_7);

    FF_63: FD1P3DX
        port map (D=>r_gdata_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_8);

    FF_62: FD1P3DX
        port map (D=>r_gdata_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_9);

    FF_61: FD1P3DX
        port map (D=>r_gdata_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_10);

    FF_60: FD1P3DX
        port map (D=>rcount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_11);

    FF_59: FD1P3DX
        port map (D=>rcount_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_0);

    FF_58: FD1P3DX
        port map (D=>rcount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_1);

    FF_57: FD1P3DX
        port map (D=>rcount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_2);

    FF_56: FD1P3DX
        port map (D=>rcount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_3);

    FF_55: FD1P3DX
        port map (D=>rcount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_4);

    FF_54: FD1P3DX
        port map (D=>rcount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_5);

    FF_53: FD1P3DX
        port map (D=>rcount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_6);

    FF_52: FD1P3DX
        port map (D=>rcount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_7);

    FF_51: FD1P3DX
        port map (D=>rcount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_8);

    FF_50: FD1P3DX
        port map (D=>rcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_9);

    FF_49: FD1P3DX
        port map (D=>rcount_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_10);

    FF_48: FD1P3DX
        port map (D=>rcount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_11);

    FF_47: FD1S3DX
        port map (D=>w_gcount_0, CK=>RdClock, CD=>Reset, Q=>w_gcount_r0);

    FF_46: FD1S3DX
        port map (D=>w_gcount_1, CK=>RdClock, CD=>Reset, Q=>w_gcount_r1);

    FF_45: FD1S3DX
        port map (D=>w_gcount_2, CK=>RdClock, CD=>Reset, Q=>w_gcount_r2);

    FF_44: FD1S3DX
        port map (D=>w_gcount_3, CK=>RdClock, CD=>Reset, Q=>w_gcount_r3);

    FF_43: FD1S3DX
        port map (D=>w_gcount_4, CK=>RdClock, CD=>Reset, Q=>w_gcount_r4);

    FF_42: FD1S3DX
        port map (D=>w_gcount_5, CK=>RdClock, CD=>Reset, Q=>w_gcount_r5);

    FF_41: FD1S3DX
        port map (D=>w_gcount_6, CK=>RdClock, CD=>Reset, Q=>w_gcount_r6);

    FF_40: FD1S3DX
        port map (D=>w_gcount_7, CK=>RdClock, CD=>Reset, Q=>w_gcount_r7);

    FF_39: FD1S3DX
        port map (D=>w_gcount_8, CK=>RdClock, CD=>Reset, Q=>w_gcount_r8);

    FF_38: FD1S3DX
        port map (D=>w_gcount_9, CK=>RdClock, CD=>Reset, Q=>w_gcount_r9);

    FF_37: FD1S3DX
        port map (D=>w_gcount_10, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r10);

    FF_36: FD1S3DX
        port map (D=>r_gcount_0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w0);

    FF_35: FD1S3DX
        port map (D=>r_gcount_1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w1);

    FF_34: FD1S3DX
        port map (D=>r_gcount_2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w2);

    FF_33: FD1S3DX
        port map (D=>r_gcount_3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w3);

    FF_32: FD1S3DX
        port map (D=>r_gcount_4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w4);

    FF_31: FD1S3DX
        port map (D=>r_gcount_5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w5);

    FF_30: FD1S3DX
        port map (D=>r_gcount_6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w6);

    FF_29: FD1S3DX
        port map (D=>r_gcount_7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w7);

    FF_28: FD1S3DX
        port map (D=>r_gcount_8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w8);

    FF_27: FD1S3DX
        port map (D=>r_gcount_9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w9);

    FF_26: FD1S3DX
        port map (D=>r_gcount_10, CK=>WrClock, CD=>rRst, Q=>r_gcount_w10);

    FF_25: FD1S3DX
        port map (D=>r_gcount_11, CK=>WrClock, CD=>rRst, Q=>r_gcount_w11);

    FF_24: FD1S3DX
        port map (D=>w_gcount_r0, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r20);

    FF_23: FD1S3DX
        port map (D=>w_gcount_r1, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r21);

    FF_22: FD1S3DX
        port map (D=>w_gcount_r2, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r22);

    FF_21: FD1S3DX
        port map (D=>w_gcount_r3, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r23);

    FF_20: FD1S3DX
        port map (D=>w_gcount_r4, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r24);

    FF_19: FD1S3DX
        port map (D=>w_gcount_r5, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r25);

    FF_18: FD1S3DX
        port map (D=>w_gcount_r6, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r26);

    FF_17: FD1S3DX
        port map (D=>w_gcount_r7, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r27);

    FF_16: FD1S3DX
        port map (D=>w_gcount_r8, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r28);

    FF_15: FD1S3DX
        port map (D=>w_gcount_r9, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r29);

    FF_14: FD1S3DX
        port map (D=>w_gcount_r10, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r210);

    FF_13: FD1S3DX
        port map (D=>r_gcount_w0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w20);

    FF_12: FD1S3DX
        port map (D=>r_gcount_w1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w21);

    FF_11: FD1S3DX
        port map (D=>r_gcount_w2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w22);

    FF_10: FD1S3DX
        port map (D=>r_gcount_w3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w23);

    FF_9: FD1S3DX
        port map (D=>r_gcount_w4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w24);

    FF_8: FD1S3DX
        port map (D=>r_gcount_w5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w25);

    FF_7: FD1S3DX
        port map (D=>r_gcount_w6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w26);

    FF_6: FD1S3DX
        port map (D=>r_gcount_w7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w27);

    FF_5: FD1S3DX
        port map (D=>r_gcount_w8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w28);

    FF_4: FD1S3DX
        port map (D=>r_gcount_w9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w29);

    FF_3: FD1S3DX
        port map (D=>r_gcount_w10, CK=>WrClock, CD=>rRst, 
            Q=>r_gcount_w210);

    FF_2: FD1S3DX
        port map (D=>r_gcount_w11, CK=>WrClock, CD=>rRst, 
            Q=>r_gcount_w211);

    FF_1: FD1S3BX
        port map (D=>empty_d, CK=>RdClock, PD=>rRst, Q=>empty_i);

    FF_0: FD1S3DX
        port map (D=>full_d, CK=>WrClock, CD=>Reset, Q=>full_i);

    w_gctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>w_gctr_ci, S0=>open, 
            S1=>open);

    w_gctr_0: CU2
        port map (CI=>w_gctr_ci, PC0=>wcount_0, PC1=>wcount_1, CO=>co0, 
            NC0=>iwcount_0, NC1=>iwcount_1);

    w_gctr_1: CU2
        port map (CI=>co0, PC0=>wcount_2, PC1=>wcount_3, CO=>co1, 
            NC0=>iwcount_2, NC1=>iwcount_3);

    w_gctr_2: CU2
        port map (CI=>co1, PC0=>wcount_4, PC1=>wcount_5, CO=>co2, 
            NC0=>iwcount_4, NC1=>iwcount_5);

    w_gctr_3: CU2
        port map (CI=>co2, PC0=>wcount_6, PC1=>wcount_7, CO=>co3, 
            NC0=>iwcount_6, NC1=>iwcount_7);

    w_gctr_4: CU2
        port map (CI=>co3, PC0=>wcount_8, PC1=>wcount_9, CO=>co4, 
            NC0=>iwcount_8, NC1=>iwcount_9);

    w_gctr_5: CU2
        port map (CI=>co4, PC0=>wcount_10, PC1=>scuba_vlo, CO=>co5, 
            NC0=>iwcount_10, NC1=>open);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    r_gctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>r_gctr_ci, S0=>open, 
            S1=>open);

    r_gctr_0: CU2
        port map (CI=>r_gctr_ci, PC0=>rcount_0, PC1=>rcount_1, CO=>co0_1, 
            NC0=>ircount_0, NC1=>ircount_1);

    r_gctr_1: CU2
        port map (CI=>co0_1, PC0=>rcount_2, PC1=>rcount_3, CO=>co1_1, 
            NC0=>ircount_2, NC1=>ircount_3);

    r_gctr_2: CU2
        port map (CI=>co1_1, PC0=>rcount_4, PC1=>rcount_5, CO=>co2_1, 
            NC0=>ircount_4, NC1=>ircount_5);

    r_gctr_3: CU2
        port map (CI=>co2_1, PC0=>rcount_6, PC1=>rcount_7, CO=>co3_1, 
            NC0=>ircount_6, NC1=>ircount_7);

    r_gctr_4: CU2
        port map (CI=>co3_1, PC0=>rcount_8, PC1=>rcount_9, CO=>co4_1, 
            NC0=>ircount_8, NC1=>ircount_9);

    r_gctr_5: CU2
        port map (CI=>co4_1, PC0=>rcount_10, PC1=>rcount_11, CO=>co5_1, 
            NC0=>ircount_10, NC1=>ircount_11);

    empty_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>rden_i, B0=>scuba_vlo, B1=>rden_i, 
            CI=>scuba_vlo, COUT=>cmp_ci, S0=>open, S1=>open);

    empty_cmp_0: AGEB2
        port map (A0=>rcount_0, A1=>rcount_1, B0=>scuba_vlo, 
            B1=>wcount_r0, CI=>cmp_ci, GE=>co0_2);

    empty_cmp_1: AGEB2
        port map (A0=>rcount_2, A1=>rcount_3, B0=>wcount_r1, 
            B1=>wcount_r2, CI=>co0_2, GE=>co1_2);

    empty_cmp_2: AGEB2
        port map (A0=>rcount_4, A1=>rcount_5, B0=>wcount_r3, 
            B1=>wcount_r4, CI=>co1_2, GE=>co2_2);

    empty_cmp_3: AGEB2
        port map (A0=>rcount_6, A1=>rcount_7, B0=>wcount_r5, 
            B1=>wcount_r6, CI=>co2_2, GE=>co3_2);

    empty_cmp_4: AGEB2
        port map (A0=>rcount_8, A1=>rcount_9, B0=>w_g2b_xor_cluster_0, 
            B1=>wcount_r8, CI=>co3_2, GE=>co4_2);

    empty_cmp_5: AGEB2
        port map (A0=>rcount_10, A1=>empty_cmp_set, B0=>wcount_r9, 
            B1=>empty_cmp_clr, CI=>co4_2, GE=>empty_d_c);

    a0: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>empty_d_c, COUT=>open, S0=>empty_d, 
            S1=>open);

    full_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>wren_i, B0=>scuba_vlo, B1=>wren_i, 
            CI=>scuba_vlo, COUT=>cmp_ci_1, S0=>open, S1=>open);

    full_cmp_0: AGEB2
        port map (A0=>wcount_0, A1=>wcount_1, B0=>rcount_w1, 
            B1=>rcount_w2, CI=>cmp_ci_1, GE=>co0_3);

    full_cmp_1: AGEB2
        port map (A0=>wcount_2, A1=>wcount_3, B0=>rcount_w3, 
            B1=>rcount_w4, CI=>co0_3, GE=>co1_3);

    full_cmp_2: AGEB2
        port map (A0=>wcount_4, A1=>wcount_5, B0=>rcount_w5, 
            B1=>rcount_w6, CI=>co1_3, GE=>co2_3);

    full_cmp_3: AGEB2
        port map (A0=>wcount_6, A1=>wcount_7, B0=>rcount_w7, 
            B1=>r_g2b_xor_cluster_0, CI=>co2_3, GE=>co3_3);

    full_cmp_4: AGEB2
        port map (A0=>wcount_8, A1=>wcount_9, B0=>rcount_w9, 
            B1=>rcount_w10, CI=>co3_3, GE=>co4_3);

    full_cmp_5: AGEB2
        port map (A0=>full_cmp_set, A1=>scuba_vlo, B0=>full_cmp_clr, 
            B1=>scuba_vlo, CI=>co4_3, GE=>full_d_c);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    a1: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>full_d_c, COUT=>open, S0=>full_d, 
            S1=>open);

    Empty <= empty_i;
    Full <= full_i;
end Structure;

-- synopsys translate_off
library ecp3;
configuration Structure_CON of fifo_1024x16x8 is
    for Structure
        for all:AGEB2 use entity ecp3.AGEB2(V); end for;
        for all:AND2 use entity ecp3.AND2(V); end for;
        for all:CU2 use entity ecp3.CU2(V); end for;
        for all:FADD2B use entity ecp3.FADD2B(V); end for;
        for all:FD1P3BX use entity ecp3.FD1P3BX(V); end for;
        for all:FD1P3DX use entity ecp3.FD1P3DX(V); end for;
        for all:FD1S3BX use entity ecp3.FD1S3BX(V); end for;
        for all:FD1S3DX use entity ecp3.FD1S3DX(V); end for;
        for all:INV use entity ecp3.INV(V); end for;
        for all:OR2 use entity ecp3.OR2(V); end for;
        for all:ROM16X1A use entity ecp3.ROM16X1A(V); end for;
        for all:VHI use entity ecp3.VHI(V); end for;
        for all:VLO use entity ecp3.VLO(V); end for;
        for all:XOR2 use entity ecp3.XOR2(V); end for;
        for all:DP16KC use entity ecp3.DP16KC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
