-- VHDL netlist generated by SCUBA Diamond_1.4_Production (87)
-- Module  Version: 3.4
--/opt/lattice/diamond/1.4/ispfpga/bin/lin/scuba -w -n lfsr -lang vhdl -synth synplify -bus_exp 7 -bb -arch ep5c00 -type lfsr -xnor_gate -stage 32 -feedback_poly 80200003 -init_seed 01 -parallel_out -e 

-- Wed Mar  7 10:24:52 2012

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp3;
use ecp3.components.all;
-- synopsys translate_on

entity lfsr is
    port (
        Clk: in  std_logic; 
        Enb: in  std_logic; 
        Rst: in  std_logic; 
        Dout: out  std_logic_vector(31 downto 0));
end lfsr;

architecture Structure of lfsr is

    -- internal signal declarations
    signal lfsr_oddparity: std_logic;
    signal lfsr_reg_out0: std_logic;
    signal lfsr_reg_out1: std_logic;
    signal lfsr_reg_out2: std_logic;
    signal lfsr_reg_out3: std_logic;
    signal lfsr_reg_out4: std_logic;
    signal lfsr_reg_out5: std_logic;
    signal lfsr_reg_out6: std_logic;
    signal lfsr_reg_out7: std_logic;
    signal lfsr_reg_out8: std_logic;
    signal lfsr_reg_out9: std_logic;
    signal lfsr_reg_out10: std_logic;
    signal lfsr_reg_out11: std_logic;
    signal lfsr_reg_out12: std_logic;
    signal lfsr_reg_out13: std_logic;
    signal lfsr_reg_out14: std_logic;
    signal lfsr_reg_out15: std_logic;
    signal lfsr_reg_out16: std_logic;
    signal lfsr_reg_out17: std_logic;
    signal lfsr_reg_out18: std_logic;
    signal lfsr_reg_out19: std_logic;
    signal lfsr_reg_out20: std_logic;
    signal lfsr_reg_out21: std_logic;
    signal lfsr_reg_out22: std_logic;
    signal lfsr_reg_out23: std_logic;
    signal lfsr_reg_out24: std_logic;
    signal lfsr_reg_out25: std_logic;
    signal lfsr_reg_out26: std_logic;
    signal lfsr_reg_out27: std_logic;
    signal lfsr_reg_out28: std_logic;
    signal lfsr_reg_out29: std_logic;
    signal lfsr_reg_out31: std_logic;
    signal lfsr_reg_out30: std_logic;

    -- local component declarations
    component FD1P3IX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1P3JX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            PD: in  std_logic; Q: out  std_logic);
    end component;
    component ROM16X1A
        generic (INITVAL : in std_logic_vector(15 downto 0));
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;

begin
    -- component instantiation statements
    LUT4_0: ROM16X1A
        generic map (initval=> X"9669")
        port map (AD3=>lfsr_reg_out0, AD2=>lfsr_reg_out1, 
            AD1=>lfsr_reg_out21, AD0=>lfsr_reg_out31, 
            DO0=>lfsr_oddparity);

    FF_31: FD1P3JX
        port map (D=>lfsr_oddparity, SP=>Enb, CK=>Clk, PD=>Rst, 
            Q=>lfsr_reg_out0);

    FF_30: FD1P3IX
        port map (D=>lfsr_reg_out0, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out1);

    FF_29: FD1P3IX
        port map (D=>lfsr_reg_out1, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out2);

    FF_28: FD1P3IX
        port map (D=>lfsr_reg_out2, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out3);

    FF_27: FD1P3IX
        port map (D=>lfsr_reg_out3, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out4);

    FF_26: FD1P3IX
        port map (D=>lfsr_reg_out4, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out5);

    FF_25: FD1P3IX
        port map (D=>lfsr_reg_out5, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out6);

    FF_24: FD1P3IX
        port map (D=>lfsr_reg_out6, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out7);

    FF_23: FD1P3IX
        port map (D=>lfsr_reg_out7, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out8);

    FF_22: FD1P3IX
        port map (D=>lfsr_reg_out8, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out9);

    FF_21: FD1P3IX
        port map (D=>lfsr_reg_out9, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out10);

    FF_20: FD1P3IX
        port map (D=>lfsr_reg_out10, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out11);

    FF_19: FD1P3IX
        port map (D=>lfsr_reg_out11, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out12);

    FF_18: FD1P3IX
        port map (D=>lfsr_reg_out12, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out13);

    FF_17: FD1P3IX
        port map (D=>lfsr_reg_out13, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out14);

    FF_16: FD1P3IX
        port map (D=>lfsr_reg_out14, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out15);

    FF_15: FD1P3IX
        port map (D=>lfsr_reg_out15, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out16);

    FF_14: FD1P3IX
        port map (D=>lfsr_reg_out16, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out17);

    FF_13: FD1P3IX
        port map (D=>lfsr_reg_out17, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out18);

    FF_12: FD1P3IX
        port map (D=>lfsr_reg_out18, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out19);

    FF_11: FD1P3IX
        port map (D=>lfsr_reg_out19, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out20);

    FF_10: FD1P3IX
        port map (D=>lfsr_reg_out20, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out21);

    FF_9: FD1P3IX
        port map (D=>lfsr_reg_out21, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out22);

    FF_8: FD1P3IX
        port map (D=>lfsr_reg_out22, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out23);

    FF_7: FD1P3IX
        port map (D=>lfsr_reg_out23, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out24);

    FF_6: FD1P3IX
        port map (D=>lfsr_reg_out24, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out25);

    FF_5: FD1P3IX
        port map (D=>lfsr_reg_out25, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out26);

    FF_4: FD1P3IX
        port map (D=>lfsr_reg_out26, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out27);

    FF_3: FD1P3IX
        port map (D=>lfsr_reg_out27, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out28);

    FF_2: FD1P3IX
        port map (D=>lfsr_reg_out28, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out29);

    FF_1: FD1P3IX
        port map (D=>lfsr_reg_out29, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out30);

    FF_0: FD1P3IX
        port map (D=>lfsr_reg_out30, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out31);

    Dout(0) <= lfsr_reg_out0;
    Dout(1) <= lfsr_reg_out1;
    Dout(2) <= lfsr_reg_out2;
    Dout(3) <= lfsr_reg_out3;
    Dout(4) <= lfsr_reg_out4;
    Dout(5) <= lfsr_reg_out5;
    Dout(6) <= lfsr_reg_out6;
    Dout(7) <= lfsr_reg_out7;
    Dout(8) <= lfsr_reg_out8;
    Dout(9) <= lfsr_reg_out9;
    Dout(10) <= lfsr_reg_out10;
    Dout(11) <= lfsr_reg_out11;
    Dout(12) <= lfsr_reg_out12;
    Dout(13) <= lfsr_reg_out13;
    Dout(14) <= lfsr_reg_out14;
    Dout(15) <= lfsr_reg_out15;
    Dout(16) <= lfsr_reg_out16;
    Dout(17) <= lfsr_reg_out17;
    Dout(18) <= lfsr_reg_out18;
    Dout(19) <= lfsr_reg_out19;
    Dout(20) <= lfsr_reg_out20;
    Dout(21) <= lfsr_reg_out21;
    Dout(22) <= lfsr_reg_out22;
    Dout(23) <= lfsr_reg_out23;
    Dout(24) <= lfsr_reg_out24;
    Dout(25) <= lfsr_reg_out25;
    Dout(26) <= lfsr_reg_out26;
    Dout(27) <= lfsr_reg_out27;
    Dout(28) <= lfsr_reg_out28;
    Dout(29) <= lfsr_reg_out29;
    Dout(30) <= lfsr_reg_out30;
    Dout(31) <= lfsr_reg_out31;
end Structure;

-- synopsys translate_off
library ecp3;
configuration Structure_CON of lfsr is
    for Structure
        for all:FD1P3IX use entity ecp3.FD1P3IX(V); end for;
        for all:FD1P3JX use entity ecp3.FD1P3JX(V); end for;
        for all:ROM16X1A use entity ecp3.ROM16X1A(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
